### ISSUE TITLE
[Bug] Blog composables not working when no types and categories are found

### ISSUE THREAD

**Issue by lixiang810** [vuepress-theme-hope/vuepress-theme-hope#1517]
## Describe the bug

复现步骤：

1. clone [该 repo](https://github.com/lixiang810/tppi)
2. pnpm i
3. pnpm build 或 pnpm dev 或 pnpm clean-dev

输出结果（这是 build 的输出结果，如果是 dev 的话，这会输出在浏览器 console 上）：

```bash
TypeError: Cannot read properties of undefined (reading 'path')
    at ReactiveEffect.fn (C:\Other\project\tpppi\dist\.server\app.js:3251:160)
    at ReactiveEffect.run (C:\Other\project\tpppi\node_modules\.pnpm\@vue+reactivity@3.2.31\node_modules\@vue\reactivity\dist\reactivity.cjs.prod.js:139:25)
    at ComputedRefImpl.get value [as value] (C:\Other\project\tpppi\node_modules\.pnpm\@vue+reactivity@3.2.31\node_modules\@vue\reactivity\dist\reactivity.cjs.prod.js:1021:39)
    at C:\Other\project\tpppi\dist\.server\app.js:3780:54
    at C:\Other\project\tpppi\node_modules\.pnpm\@vue+runtime-core@3.2.31\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:2804:35
    at renderFnWithContext (C:\Other\project\tpppi\node_modules\.pnpm\@vue+runtime-core@3.2.31\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:535:21)
    at Object.ssrRenderSlot (C:\Other\project\tpppi\node_modules\.pnpm\@vue+server-renderer@3.2.31_vue@3.2.31\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:638:21)
    at _sfc_ssrRender$3 (C:\Other\project\tpppi\dist\.server\app.js:1942:20)
    at renderComponentSubTree (C:\Other\project\tpppi\node_modules\.pnpm\@vue+server-renderer@3.2.31_vue@3.2.31\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:266:13)
    at renderComponentVNode (C:\Other\project\tpppi\node_modules\.pnpm\@vue+server-renderer@3.2.31_vue@3.2.31\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:211:16)
 ELIFECYCLE  Command failed with exit code 1.
```

## Additional context

环境：Windows 11
浏览器：Mozilla Firefox Nightly 和 Microsoft Edge
Node 版本：Nodejs 16.14.0
pnpm 版本：6.32.2

**Comment by Mister-Hope** [comment]
这是一个很有趣的问题，经查阅，因为你没有设置任何非主页页面。

由于你的博客是单语言，因此博客插件不会遍历多语言，而由于主页不能视作文章，这导致博客插件没有可以获取到任何一篇文章，进而没有办法生成对应的路径。

这是一个edge case，为了解决它我需要增加额外的判断和代码，而正常使用中不可能出现使用博客插件，但项目里只有主页的情况  (home: true in fronmatter) 所以我不认为它是一个bug。

**Comment by Mister-Hope** [comment]
最明确的解决方案是随便加一个什么页面，比如你的个人介绍页，一切都会正常工作。

**Comment by Mister-Hope** [comment]
重新想了一下，可能会有人在多语言项目中，仅对多语言中的某些语言设置主页。这里最好还是规避一下。

**Comment by lixiang810** [comment]
> 最明确的解决方案是随便加一个什么页面，比如你的个人介绍页，一切都会正常工作。

简单再测试了一下，相关代码已经 push 上去了。在 docs 下创建 intro.md，当 intro.md 设为 `article: false` 后问题依旧，但如果设为 true 则无此问题，可以正常 build 与 dev（含 clean-dev）。

这个 bug 可以认为已经排除到了，接下来我会尝试加入自定义组件。
