### ISSUE TITLE
[Bug] TypeError: (0 , import_vuepress_theme_hope.defineNavbarConfig) is not a function

### ISSUE THREAD

**Issue by jsf-3shape** [vuepress-theme-hope/vuepress-theme-hope#1815]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

```javascript
> vuepress build src

TypeError: (0 , import_vuepress_theme_hope.defineNavbarConfig) is not a function
    at Object.<anonymous> (/home/runner/work/CRMLogicApps/CRMLogicApps/docs/src/.vuepress/navbar.ts:24:72)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.require.extensions..ts (/home/runner/work/CRMLogicApps/CRMLogicApps/docs/node_modules/vuepress/node_modules/@vuepress/cli/lib/utils/allowTs.js:11:11)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/CRMLogicApps/CRMLogicApps/docs/src/.vuepress/themeConfig.ts:27:29)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.require.extensions..ts (/home/runner/work/CRMLogicApps/CRMLogicApps/docs/node_modules/vuepress/node_modules/@vuepress/cli/lib/utils/allowTs.js:11:11)
Error: Process completed with exit code 1.
```

### Additional context

No changes to the code in host project. Only dependency update to latest version of this library.

**Comment by Mister-Hope** [comment]
Check changelog

**Comment by jsf-3shape** [comment]
My bad. Thanks.... everything is working again.
