### ISSUE TITLE
[Bug]The project can not launch after install fallowing offical installation

### ISSUE THREAD

**Issue by seasideccm** [vuepress-theme-hope/vuepress-theme-hope#1981]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Uncaught (in promise) Error: useRouteLocale() is called without provider.
    at useRouteLocale (chunk-OOQFWU6B.js:79:11)
    at f (browser.ts:13:14)
    at l (icons.ts:8:3)
    at Object.setup (config.ts:9:5)
    at setup (app.js:249:29)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)
    at setupComponent (runtime-core.esm-bundler.js:7120:11)
    at mountComponent (runtime-core.esm-bundler.js:5473:13)
    at processComponent (runtime-core.esm-bundler.js:5448:17)

### Additional context

pnpm create vuepress-theme-hope@next docs
.
.
.

Successful Generated!
? Would you like to preview template now? Yes
Staring dev server...

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/vuepress-next/commit/eb962a057a91142a46a071896de418bc9903c388

Use beta.47

**Comment by Mister-Hope** [comment]
Seems to be effected by https://github.com/vuepress/vuepress-next/commit/de6b43dc718537469224ccf93fb826e6a0ea9f83

**Comment by Mister-Hope** [comment]
beta82 should be compatable with latest vp2

**Comment by seasideccm** [comment]
beta82 worked
