### ISSUE TITLE
 Cannot use 'in' operator to search for 'global' in undefined [Bug]

### ISSUE THREAD

**Issue by 2064135029** [vuepress-theme-hope/vuepress-theme-hope#2069]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

TypeError: Cannot use 'in' operator to search for 'global' in undefined
    at covertThemeConfig (/Users/wujh/webDoc/node_modules/vuepress-theme-hope/lib/node/compact/theme.js:149:22)
    at defineThemeConfig (/Users/wujh/webDoc/node_modules/vuepress-theme-hope/lib/node/compact/helper-v2.js:44:42)
    at Object.<anonymous> (/Users/wujh/webDoc/docs/.vuepress/themeConfig.ts:29:76)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.require.extensions..ts (/Users/wujh/webDoc/node_modules/@vuepress/cli/lib/utils/allowTs.js:11:11)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/wujh/webDoc/docs/.vuepress/config.ts:27:34)
error Command failed with exit code 1.

**Comment by Mister-Hope** [comment]
What's your node version?

**Comment by 2064135029** [comment]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/23395177/179138435-264a0f5b-fce8-4182-b25a-71c5c7a6bba0.png">

**Comment by 2064135029** [comment]
> ![image](https://user-images.githubusercontent.com/33315834/178984042-64c80cde-6564-4ca6-b80a-56bbf0a99221.png)
> 
> I am wondering what value do you set for encrypt?

<img width="535" alt="image" src="https://user-images.githubusercontent.com/23395177/179138655-21d387fe-5859-4d72-b24a-bb9f02479d0e.png">

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/179147945-37dc7602-1a85-45c1-ba2f-9297614e9e98.png)

This doesnot explain why : 

```
TypeError: Cannot use 'in' operator to search for 'global' in undefined
at covertThemeConfig (/Users/wujh/webDoc/node_modules/vuepress-theme-hope/lib/node/compact/theme.js:149:22)
```

I can not reproduce it. A mininal reproduction is required.
