### ISSUE TITLE
[Bug] Can not build docs: Error: Missing "./preload-helper" export in "vite" package

### ISSUE THREAD

**Issue by snowyu** [vuepress-theme-hope/vuepress-theme-hope#2145]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

```bash
pnpm docs:vite-build
...
docs/md-enhance docs:vite-build: [vite:resolve] Missing "./preload-helper" export in "vite" package
docs/md-enhance docs:vite-build: ✖ Compiling with vite - failed
docs/md-enhance docs:vite-build: Error: Missing "./preload-helper" export in "vite" package
docs/md-enhance docs:vite-build:     at bail (./vuepress-theme-hope/node_modules/.pnpm/vite@2.9.15/node_modules/vite/dist/node/chunks/dep-689425f3.js:38597:8)
docs/md-enhance docs:vite-build:     at resolve (./vuepress-theme-hope/node_modules/.pnpm/vite@2.9.15/node_modules/vite/dist/node/chunks/dep-689425f3.js:38674:10)
docs/md-enhance docs:vite-build:     at resolveExports (./vuepress-theme-hope/node_modules/.pnpm/vite@2.9.15/node_modules/vite/dist/node/chunks/dep-689425f3.js:40982:12)
docs/md-enhance docs:vite-build:     at resolveDeepImport (./vuepress-theme-hope/node_modules/.pnpm/vite@2.9.15/node_modules/vite/dist/node/chunks/dep-689425f3.js:41000:31)
docs/md-enhance docs:vite-build:     at tryNodeResolve (./vuepress-theme-hope/node_modules/.pnpm/vite@2.9.15/node_modules/vite/dist/node/chunks/dep-689425f3.js:40773:20)
docs/md-enhance docs:vite-build:     at Object.resolveId (./vuepress-theme-hope/node_modules/.pnpm/vite@2.9.15/node_modules/vite/dist/node/chunks/dep-689425f3.js:40581:28)
docs/md-enhance docs:vite-build:     at ./vuepress-theme-hope/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/shared/rollup.js:22826:37
docs/md-enhance docs:vite-build: fatal error: all goroutines are asleep - deadlock!
```

**Comment by Mister-Hope** [comment]
vuepress2 does not support vue3 yet, will support it in next version.
