### ISSUE TITLE
[Bug] vuepress-plugin-comment2 waline type Error

### ISSUE THREAD

**Issue by qqlcx5** [vuepress-theme-hope/vuepress-theme-hope#2200]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-plugin-comment2

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/31888710/188771603-9a88f6bf-5095-49fd-ad6f-b475d95f8668.png)

**Comment by ShaoClean** [comment]
i have the same problem

**Comment by ShaoClean** [comment]
i have the same problem
<img width="1038" alt="截屏2022-09-08 15 21 34" src="https://user-images.githubusercontent.com/98806795/189060446-014894ad-6c70-4c3e-8613-b096e29f6630.png">

**Comment by Cccc-owo** [comment]
Me too.
Env: Windows 11

![1](https://user-images.githubusercontent.com/47687154/189512616-07a6aa1a-a939-46d9-b38e-8cb27df95d5a.png)
```
file:///G:/CODE/server-status/docs/.vuepress/.temp/.server/app.d6d52091.mjs:6
import { Waline } from "@waline/client/dist/component";
         ^^^^^^
SyntaxError: Named export 'Waline' not found. The requested module '@waline/client/dist/component' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@waline/client/dist/component';
const { Waline } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async file:///G:/CODE/server-status/node_modules/@vuepress/bundler-vite/dist/index.js:406:30
    at async file:///G:/CODE/server-status/node_modules/@vuepress/utils/dist/index.js:98:20
    at async build (file:///G:/CODE/server-status/node_modules/@vuepress/bundler-vite/dist/index.js:394:3)
    at async file:///G:/CODE/server-status/node_modules/@vuepress/cli/dist/index.js:228:3
error Command failed with exit code 1.
```

**Comment by Mister-Hope** [comment]
Should be fixed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/4c87572d04c75e5835eae0f249c335f0d04b70dd
