### ISSUE TITLE
[Bug] Install Error

### ISSUE THREAD

**Issue by likongshun** [vuepress-theme-hope/vuepress-theme-hope#2224]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

# 终端 屏幕 显示
```sh
D:\vuepress>npm init vuepress-theme-hope@next docs
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
? Select a language to display / 选择显示语言 english (US)
? Choose package manager npm
Updating package.json...
? Do you need a GitHub workflow to deploy docs on GitHub pages? No
? What type of project do you want to create? docs
Generating Template...
node:fs:1551
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat 'C:\Users\likon\AppData\Local\npm-cache\_npx\0c8cce8a7eeb7e99\node_modules\create-vuepress-theme-hope\assets\public'
    at statSync (node:fs:1551:3)
    at b (file:///C:/Users/likon/AppData/Local/npm-cache/_npx/0c8cce8a7eeb7e99/node_modules/create-vuepress-theme-hope/lib/index.js:2:3315)
    at q (file:///C:/Users/likon/AppData/Local/npm-cache/_npx/0c8cce8a7eeb7e99/node_modules/create-vuepress-theme-hope/lib/index.js:2:4144)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CAC.<anonymous> (file:///C:/Users/likon/AppData/Local/npm-cache/_npx/0c8cce8a7eeb7e99/node_modules/create-vuepress-theme-hope/lib/index.js:2:8443) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\Users\\likon\\AppData\\Local\\npm-cache\\_npx\\0c8cce8a7eeb7e99\\node_modules\\create-vuepress-theme-hope\\assets\\public'
}
npm ERR! code 1
npm ERR! path D:\vuepress
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-vuepress-theme-hope docs

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\likon\AppData\Local\npm-cache\_logs\2022-09-18T08_57_54_722Z-debug-0.log
```
# Log文件 2022-09-18T08_57_54_722Z-debug-0.log

```log
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\likon\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@8.19.2
2 info using node@v16.16.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\likon\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:D:\vuepress\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\likon\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\likon\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 8ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm init vuepress-theme-hope@next docs
23 verbose argv "init" "vuepress-theme-hope@next" "docs"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 1ms
26 timing npm:load:display Completed in 2ms
27 verbose logfile logs-max:10 dir:C:\Users\likon\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\likon\AppData\Local\npm-cache\_logs\2022-09-18T08_57_54_722Z-debug-0.log
29 timing npm:load:logFile Completed in 26ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 41ms
33 silly logfile start cleaning logs, removing 2 files
34 timing arborist:ctor Completed in 1ms
35 silly logfile done cleaning log files
36 http fetch GET 200 https://registry.npmjs.org/create-vuepress-theme-hope 1110ms (cache revalidated)
37 timing arborist:ctor Completed in 0ms
38 timing arborist:ctor Completed in 0ms
39 timing command:init Completed in 8780ms
40 verbose stack Error: command failed
40 verbose stack     at ChildProcess.<anonymous> (C:\Users\likon\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
40 verbose stack     at ChildProcess.emit (node:events:527:28)
40 verbose stack     at maybeClose (node:internal/child_process:1092:16)
40 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
41 verbose pkgid vuepress-theme-hope-template@2.0.0
42 verbose cwd D:\vuepress
43 verbose Windows_NT 10.0.19044
44 verbose node v16.16.0
45 verbose npm  v8.19.2
46 error code 1
47 error path D:\vuepress
48 error command failed
49 error command C:\Windows\system32\cmd.exe /d /s /c create-vuepress-theme-hope docs
50 verbose exit 1
51 timing npm Completed in 8960ms
52 verbose code 1
53 error A complete log of this run can be found in:
53 error     C:\Users\likon\AppData\Local\npm-cache\_logs\2022-09-18T08_57_54_722Z-debug-0.log
```

**Comment by HUGHNew** [comment]
the same problme
node: v16.13.1
npm: v8.1.2
vuepress v2
Ubuntu 20.04 LTS
