### ISSUE TITLE
[Bug]Initializing and preparing dataerror error in hook onInitialized from vuepress-plugin-blog2 [已解决]

### ISSUE THREAD

**Issue by Yuelioi** [vuepress-theme-hope/vuepress-theme-hope#2248]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope2

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Description

终端报错提示:
```
> vuepress dev docs --clean-cache

✔ Cleaning cache - done in 12ms
⠙ Initializing and preparing dataerror error in hook onInitialized from vuepress-plugin-blog2
✖ Initializing and preparing data - failed in 684ms
TypeError: Cannot read properties of null (reading 'replace')
    at m (file:///H:/Scripting/Vue%20Projects/docs_yuelili_com/node_modules/.pnpm/vuepress-plugin-blog2@2.0.0-beta.105/node_modules/vuepress-plugin-blog2/lib/node/index.js:14:55)
    at v (file:///H:/Scripting/Vue%20Projects/docs_yuelili_com/node_modules/.pnpm/vuepress-plugin-blog2@2.0.0-beta.105/node_modules/vuepress-plugin-blog2/lib/node/index.js:15:95)
    at file:///H:/Scripting/Vue%20Projects/docs_yuelili_com/node_modules/.pnpm/vuepress-plugin-blog2@2.0.0-beta.105/node_modules/vuepress-plugin-blog2/lib/node/index.js:15:562
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Object.process (file:///H:/Scripting/Vue%20Projects/docs_yuelili_com/node_modules/.pnpm/@vuepress+core@2.0.0-beta.51/node_modules/@vuepress/core/dist/index.js:667:26)
    at async appInit (file:///H:/Scripting/Vue%20Projects/docs_yuelili_com/node_modules/.pnpm/@vuepress+core@2.0.0-beta.51/node_modules/@vuepress/core/dist/index.js:590:3)
    at async file:///H:/Scripting/Vue%20Projects/docs_yuelili_com/node_modules/.pnpm/@vuepress+cli@2.0.0-beta.51/node_modules/@vuepress/cli/dist/index.js:484:7
    at async file:///H:/Scripting/Vue%20Projects/docs_yuelili_com/node_modules/.pnpm/@vuepress+utils@2.0.0-beta.51/node_modules/@vuepress/utils/dist/index.js:98:20
    at async dev (file:///H:/Scripting/Vue%20Projects/docs_yuelili_com/node_modules/.pnpm/@vuepress+cli@2.0.0-beta.51/node_modules/@vuepress/cli/dist/index.js:483:5)
 ELIFECYCLE  Command failed with exit code 1.
```

研究了下,是因为配置项默认使用`blog: { autoExcerpt: true }`,而我的文章模板还没有书写内容,因此报错

---
建议:

也许可以加个判断,没有内容自动跳过当前文章?

**Comment by Mister-Hope** [comment]
Give me a minimal reproduction
