### ISSUE TITLE
[Bug] Cannot find package '@internal/pagesData' when using vuepress-plugin-md-enhance

### ISSUE THREAD

**Issue by vmihailenco** [vuepress-theme-hope/vuepress-theme-hope#2326]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-plugin-md-enhance

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

I am getting the following error when compiling docs

```
✖ Rendering 40 pages - failed in 141ms
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@internal/pagesData' imported from node_modules/.pnpm/@vuepress+client@2.0.0-beta.52/node_modules/@vuepress/client/dist/chunk-X6HE2CCA.js
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
 ELIFECYCLE  Command failed with exit code 1.
```

### Additional context

- `pnpm docs:dev` works and all pages are rendered correctly.
- Removing `mdEnhancePlugin` from the plugins also fixes `pnpm docs:build`.
- Other plugins like vuepress-plugin-redirect and vuepress-plugin-seo2 work fine.
- Downgrading to prev version of vuepress-plugin-md-enhance does not help and produces a different error.

node v18.11.0
vuepress 2.0.0-beta.52
vuepress-plugin-md-enhance 2.0.0-beta.111

```js
    mdEnhancePlugin({
      mermaid: true,
    }),
```

**Comment by Mister-Hope** [comment]
Sorry but I am really busy these days about study.

Can you try make a minimal reproduction and may you try to find more details?

**Comment by Mister-Hope** [comment]
I am not be able to reproduce this issue with beta.133 with my blog. so if you guys are still contering problems, a mininal reproduction genreated from template is required.

 ( I am really BUSY these days so I do need a mininal reproduction repo to save my time.🥺)

**Comment by Mister-Hope** [comment]
Emm, if you are using vite, add this snipet to see if it works:


```
import { addViteSsrNoExternal } from 'vuepress-shared';

export dault {
  // ...
  extendsBundlerOptions: (config, app) => {
    addViteSsrNoExternal ({ app, config }, 'vuepress-shared');
  },
}
```

If it works, then we might need to decalre this in vite@~3.1, emm, a bit strange.

**Comment by Mister-Hope** [comment]
A pr is welcomed for this if you confirm this can be a solution.

**Comment by vmihailenco** [comment]
Adding `vuepress-shared` to `noExternal` fixes the issue. Thank you.

**Comment by hlassiege** [comment]
Hi,
For information, I had exactly the same issue

    "vuepress-plugin-md-enhance": "^2.0.0-beta.113",
    "vuepress": "^2.0.0-beta.52"

and your snippet above resolved it for me.

**Comment by dyywork** [comment]
> Emm, if you are using vite, add this snipet to see if it works:
> 
> ```ts
> import { addViteSsrNoExternal } from 'vuepress-shared';
> 
> export default {
>   // ...
>   extendsBundlerOptions: (config, app) => {
>     addViteSsrNoExternal ({ app, config }, 'vuepress-shared');
>   },
> }
> ```
> 
> If it works, then we might need to declare this in vite@~3.1, emm, a bit strange.
> 
> P.S.: you do need to install `vuepress-shared` when using pnpm


This error will be reported after this configuration

```
ReferenceError: Cannot access 'clientConfigs' before initialization
    at file:///home/runner/work/blog/blog/docs/.vuepress/.temp/.server/app.48[24](https://github.com/dyywork/blog/actions/runs/3317817691/jobs/5481076349#step:5:25)f8ad.mjs:465:17
    at ModuleJob.run (node:internal/modules/esm/module_job:193:[25](https://github.com/dyywork/blog/actions/runs/3317817691/jobs/5481076349#step:5:26))
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async file:///home/runner/work/blog/blog/node_modules/@vuepress/bundler-vite/dist/index.js:420:30
    at async file:///home/runner/work/blog/blog/node_modules/@vuepress/utils/dist/index.js:98:20
    at async build (file:///home/runner/work/blog/blog/node_modules/@vuepress/bundler-vite/dist/index.js:408:3)
    at async CAC.<anonymous> (file:///home/runner/work/blog/blog/node_modules/vuepress-vite/node_modules/@vuepress/cli/dist/index.js:2[28](https://github.com/dyywork/blog/actions/runs/3317817691/jobs/5481076349#step:5:29):3)
Error: Process completed with exit code 1.
```

**Comment by Mister-Hope** [comment]
Please gives some feedback about whether the issue still exisits in vp2beta.53 and my beta.114

**Comment by vmihailenco** [comment]
beta.114 still does not exist on npm for some reason: https://www.npmjs.com/package/vuepress-plugin-sitemap2

**Comment by hlassiege** [comment]
Indeed, I have the error "ReferenceError: Cannot access 'clientConfigs' before initialization" in vp2beta.53 and my beta.113

The beta 114 is not available right now for me. I'll test it as soon as I have it

**Comment by Mister-Hope** [comment]
Try again now, I have some network issues publishing beta.114, and I just republished it.

**Comment by vmihailenco** [comment]
That combination (53+114) does not work with a different message

```
✔ Initializing and preparing data - done in 387ms
⠸ Compiling with vite[commonjs--resolver] Missing "./lib/client" export in "vuepress-plugin-blog2" package
✖ Compiling with vite - failed in 2.89s
Error: Missing "./lib/client" export in "vuepress-plugin-blog2" package
    at bail (file:///home/vmihailenco/Dropbox/docs/uptrace-blog/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:33715:8)
    at resolve (file:///home/vmihailenco/Dropbox/docs/uptrace-blog/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:33792:10)
    at resolveExports (file:///home/vmihailenco/Dropbox/docs/uptrace-blog/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34853:12)
    at resolveDeepImport (file:///home/vmihailenco/Dropbox/docs/uptrace-blog/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34871:31)
    at tryNodeResolve (file:///home/vmihailenco/Dropbox/docs/uptrace-blog/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34584:20)
    at Object.resolveId (file:///home/vmihailenco/Dropbox/docs/uptrace-blog/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34357:28)
    at Object.handler (file:///home/vmihailenco/Dropbox/docs/uptrace-blog/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45996:19)
    at file:///home/vmihailenco/Dropbox/docs/uptrace-blog/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:22710:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by Mister-Hope** [comment]
> 

Are you using blog2 plugin yourself? You may need to correct exports from `lib/client` to `client`

**Comment by vmihailenco** [comment]
Yes, that helps. Now I get the same error that can be fixed with `noSsr` trick:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@internal/pagesData' imported from /home/vmihailenco/Dropbox/docs/uptrace-blog/node_modules/.pnpm/@vuepress+client@2.0.0-beta.53/node_modules/@vuepress/client/dist/chunk-X6HE2CCA.js
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
 ELIFECYCLE  Command failed with exit code 1.
```

So the fix is still needed.

**Comment by Mister-Hope** [comment]
I am still curious about his bug, as I don't know how it happends.....

**Comment by Mister-Hope** [comment]
I would prefer to figure this out, rather than "a somehow workaround".

Could you plekase try locally edit `vuepress-shared` like this in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/188b2f1cc0ce1c37df7540aed93cc917a91dc1a4 and see if it's still trigging issues?

**Comment by ClearDewy** [comment]
You can try create an empty dir and run `npm init vuepress-theme-hope@next [dir]` and select the "blog",then run `npm run docs:build`,you may meet the bug

**Comment by Mister-Hope** [comment]
It seems that it will happen in other plugins.

May need to noExternal `vuepress-shared` in all packages, but I am still curious about how it's infected by vite@3.1

**Comment by Mister-Hope** [comment]
Closing, if you are using other plugins and meet similar issues, just comment here and I will check that.

**Comment by liuyanzhou** [comment]
I use "vuepress": "^2.0.0-beta.53",  "vuepress-theme-hope": "^2.0.0-beta.122" , it appear  Uncaught ReferenceError: Cannot access 'clientConfigs' before initialization

**Comment by ronny1020** [comment]
Same issue with `vuepress-plugin-comment2": "2.0.0-beta.191` and`"vuepress": "2.0.0-beta.61"`. BTW, running dev works properly. it just happen during the build.

I use npm in windows os, and it also happens on the GitHub action.

```bash
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@internal/pagesData' imported from .......\node_modules\@vuepress\client\dist\chunk-X6BS2PXP.js
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
```
