### ISSUE TITLE
[Bug] 升级完成后 build 报错

### ISSUE THREAD

**Issue by itwanger** [vuepress-theme-hope/vuepress-theme-hope#2673]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

yarn run v1.22.10
$ vuepress build docs
vuepress-theme-hope:  ⚠ CSDN icon in blog media config not found!
✔ Initializing and preparing data - done in 19.66s
⠹ Compiling with vite[vite]: Rollup failed to resolve import "/Users/maweiqing/Documents/GitHub/toBeBetterJavaer/node_modules/vuepress-theme-hope/lib/client/layouts/404.js" from "/Users/maweiqing/Documents/GitHub/toBeBetterJavaer/docs/.vuepress/.temp/internal/layoutComponents.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
✖ Compiling with vite - failed in 27.74s
Error: [vite]: Rollup failed to resolve import "/Users/maweiqing/Documents/GitHub/toBeBetterJavaer/node_modules/vuepress-theme-hope/lib/client/layouts/404.js" from "/Users/maweiqing/Documents/GitHub/toBeBetterJavaer/docs/.vuepress/.temp/internal/layoutComponents.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///Users/maweiqing/Documents/GitHub/toBeBetterJavaer/node_modules/.pnpm/registry.npmmirror.com+vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44636:19)
    at onwarn (file:///Users/maweiqing/Documents/GitHub/toBeBetterJavaer/node_modules/.pnpm/registry.npmmirror.com+vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44407:13)
    at Object.onwarn (file:///Users/maweiqing/Documents/GitHub/toBeBetterJavaer/node_modules/.pnpm/registry.npmmirror.com+rollup@3.10.0/node_modules/rollup/dist/es/shared/rollup.js:24457:13)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/maweiqing/Documents/GitHub/toBeBetterJavaer/node_modules/.pnpm/registry.npmmirror.com+rollup@3.10.0/node_modules/rollup/dist/es/shared/rollup.js:23139:26)
    at ModuleLoader.resolveDynamicImport (file:///Users/maweiqing/Documents/GitHub/toBeBetterJavaer/node_modules/.pnpm/registry.npmmirror.com+rollup@3.10.0/node_modules/rollup/dist/es/shared/rollup.js:23195:58)
    at async file:///Users/maweiqing/Documents/GitHub/toBeBetterJavaer/node_modules/.pnpm/registry.npmmirror.com+rollup@3.10.0/node_modules/rollup/dist/es/shared/rollup.js:23084:32
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/6011374/212510603-6ba7394a-c893-43b0-8e91-19e3f8a354b1.png">

**Comment by Mister-Hope** [comment]
Reproduction is needed, and I will close this if not further response

**Comment by rosendolu** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/42633099/3b4d67df-5810-44e7-8ecc-ad2296355d9c)
Same Error

**Comment by Mister-Hope** [comment]
> Reproduction is needed, and I will close this if not further response
