### ISSUE TITLE
[Bug] no such file or directory, lstat 'D:/Git/GitHub/journal/node_modules/vuepress-plugin-sitemap2/templates/sitemap.xsl (beta 161)

### ISSUE THREAD

**Issue by JeremieLitzler** [vuepress-theme-hope/vuepress-theme-hope#2681]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Hi,

Following the upgrade from beta 158 to 161 of the theme, I see this problem on build:

```
vuepress-plugin-sitemap2:  ⠋ Generating sitemap to /sitemap.xmlnode:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'D:/Git/GitHub/journal/node_modules/vuepress-plugin-sitemap2/templates/sitemap.xsl'
    at Object.lstatSync (node:fs:1514:3)
    at Object.lstatSync (D:\Git\GitHub\journal\node_modules\graceful-fs\polyfills.js:318:34)
    at statFunc (D:\Git\GitHub\journal\node_modules\fs-extra\lib\util\stat.js:24:20)
    at getStatsSync (D:\Git\GitHub\journal\node_modules\fs-extra\lib\util\stat.js:25:19)
    at Object.checkPathsSync (D:\Git\GitHub\journal\node_modules\fs-extra\lib\util\stat.js:67:33)
    at Object.copySync (D:\Git\GitHub\journal\node_modules\fs-extra\lib\copy\copy-sync.js:27:38)
    at WriteStream.<anonymous> (file:///D:/Git/GitHub/journal/node_modules/vuepress-plugin-sitemap2/lib/node/index.js:4:7)
    at WriteStream.emit (node:events:402:35)
    at finish (node:internal/streams/writable:750:10)
    at finishMaybe (node:internal/streams/writable:735:9)
    at afterWrite (node:internal/streams/writable:504:3)
    at onwrite (node:internal/streams/writable:477:7)
    at node:internal/fs/streams:443:5
    at FSReqCallback.wrapper [as oncomplete] (node:fs:903:5) {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'D:/Git/GitHub/journal/node_modules/vuepress-plugin-sitemap2/templates/sitemap.xsl'
}
```

I did remove the entire node_modules and yarn.lock file before launching the build

You can replicate on https://github.com/JeremieLitzler/journal/tree/upgradeToVuePressTheme161

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/pull/2680
