### ISSUE TITLE
[Bug] (Regression 2.0.0-beta.164) - Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by NicolasThierion** [vuepress-theme-hope/vuepress-theme-hope#2691]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

- When using `vuepress build docs --config ./vuepress.config.ts`, I have this error: 
  ```
  TypeError: Cannot read properties of undefined (reading 'map')
      at Proxy.<anonymous> (file:///tmp/m3-press/.vuepress/.temp/.server/app.48c7f2eb.mjs:2452:41)
      at renderComponentRoot (/tmp/m3-press/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:891:44)
      at renderComponentSubTree (/tmp/m3-press/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:260:51)
      at renderComponentVNode (/tmp/m3-press/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
      at renderVNode (/tmp/m3-press/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:296:22)
      at renderVNodeChildren (/tmp/m3-press/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:311:9)
      at renderElementVNode (/tmp/m3-press/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:362:17)
      at renderVNode (/tmp/m3-press/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:293:17)
      at renderVNodeChildren (/tmp/m3-press/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:311:9)
      at renderVNode (/tmp/m3-press/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:288:13)
  ```
- It does not happen with `vuepress dev docs --config ./vuepress.config.ts`
- It was working fine  2.0.0-beta.163, but not on 2.0.0-beta.164
- This is the faulty block in `app.48c7f2eb.mjs:2452:41`:
  ```js{8}
  const navbarLayout = computed(() => themeLocale.value.navbarLayout || {
    // ...
    return () => {
      // ...
            (_a = slots["startBefore"]) == null ? void 0 : _a.call(slots),
            ...navbarLayout.value.start.map((item) => map[item]),
            (_b = slots["startAfter"]) == null ? void 0 : _b.call(slots)
          ]),

  ``` 

I suspect it is due to this change mentionned within the changelog: 
> - **theme:** left/right options in navbarLayout renamed to start/end and slot name changes as well.

====
PS: Nice work by the way, and thank you.

**Comment by Mister-Hope** [comment]
Yes, that change is targeting rtl layout
