### ISSUE TITLE
[Bug] Issue with @vuepress/plugin-docsearch on build

### ISSUE THREAD

**Issue by JeremieLitzler** [vuepress-theme-hope/vuepress-theme-hope#2743]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Hello @Mister-Hope 

I've just installed the beta.172.

At first, the build worked after a `yarn upgrade vuepress-theme-hope@2.0.0-beta.172`.
But once on Netlify, it failed:

```
6:53:48 PM: ✔ Compiling with vite - done in 17.73s
6:53:48 PM: - Rendering 262 pages
6:53:48 PM: [Vue warn]: Unhandled error during execution of setup function
6:53:48 PM:   at <VuepressApp>
6:53:48 PM: ✖ Rendering 262 pages - failed in 131ms
6:53:48 PM: Error: usePageHead() is called without provider.
6:53:48 PM:     at usePageHead (file:///opt/build/repo/docs/.vuepress/.temp/.server/app.cc6eb54b.mjs:2664:11)
6:53:48 PM:     at setupUpdateHead (file:///opt/build/repo/docs/.vuepress/.temp/.server/app.cc6eb54b.mjs:8716:16)
6:53:48 PM:     at setup (file:///opt/build/repo/docs/.vuepress/.temp/.server/app.cc6eb54b.mjs:8734:7)
6:53:48 PM:     at callWithErrorHandling (/opt/build/repo/node_modules/@vuepress/bundler-vite/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
6:53:48 PM:     at setupStatefulComponent (/opt/build/repo/node_modules/@vuepress/bundler-vite/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7176:29)
6:53:48 PM:     at setupComponent (/opt/build/repo/node_modules/@vuepress/bundler-vite/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7131:11)
6:53:48 PM:     at renderComponentVNode (/opt/build/repo/node_modules/@vuepress/bundler-vite/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
6:53:48 PM:     at renderToString (/opt/build/repo/node_modules/@vuepress/bundler-vite/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:447:26)
6:53:48 PM:     at renderPage (file:///opt/build/repo/node_modules/@vuepress/bundler-vite/dist/index.js:361:30)
6:53:48 PM:     at async file:///opt/build/repo/node_modules/@vuepress/bundler-vite/dist/index.js:431:7
```

So I removed the node_modules and the yarn.lock locally and launched the compilation: this time, it failed.

```
✔ Initializing and preparing data - done in 35.15s
⠦ Compiling with vite[vite:load-fallback] Could not load D:/Git/GitHub/journal/docs/.vuepress/.temp/internal/layoutComponents (imported by node_modules/@vuepress/plugin-docsearch/node_modules/@vuepress/client/dist/chunk-V3MKNX2O.js): ENOENT: no such file or directory, open 'D:\Git\GitHub\journal\docs\.vuepress\.temp\internal\layoutComponents'
✖ Compiling with vite - failed in 37.06s
Error: Could not load D:/Git/GitHub/journal/docs/.vuepress/.temp/internal/layoutComponents (imported by node_modules/@vuepress/plugin-docsearch/node_modules/@vuepress/client/dist/chunk-V3MKNX2O.js): ENOENT: no such file or directory, open 'D:\Git\GitHub\journal\docs\.vuepress\.temp\internal\layoutComponents'
```

Is it from the version you've just released?

Thanks.

**Comment by JeremieLitzler** [comment]
@Mister-Hope 

Actually, it is not the beta 172: it is `plugin-docsearch`. It is weird, because I published [my website yesterday](https://github.com/JeremieLitzler/journal/commit/ef546c4d222bb58c086854edc76d092762c63151) without any issue.

**Comment by JeremieLitzler** [comment]
You can reproduce it using [my public repository](https://github.com/JeremieLitzler/journal).

**Comment by JeremieLitzler** [comment]
I don't know if it can help: I tried to use `pnpm` instead of `yarn` and I see this warning:

```
 WARN  Issues with peer dependencies found
.
├─┬ @vuepress/plugin-docsearch 2.0.0-beta.50-pre.1
│ └─┬ @docsearch/js 3.3.2
│   └─┬ @docsearch/react 3.3.2
│     └─┬ @algolia/autocomplete-preset-algolia 1.7.4
│       └── ✕ missing peer @algolia/client-search@">= 4.9.1 < 6"
└─┬ vuepress-vite 2.0.0-beta.60
  ├── ✕ missing peer vue@^3.2.45
  └── ✕ missing peer @vuepress/client@2.0.0-beta.60
Peer dependencies that should be installed:
  @algolia/client-search@">= 4.9.1 < 6"  @vuepress/client@2.0.0-beta.60         vue@^3.2.45
```

**Comment by JeremieLitzler** [comment]
I got it: somehow, running `yarn add -D @vuepress/plugin-docsearch@next` yesterday to add docsearch added the dev dependency as `"@vuepress/plugin-docsearch": "^2.0.0-beta.60"`. 

Updating to `"@vuepress/plugin-docsearch": "2.0.0-beta.60"` solved the issue.

I'd love to understand why.

Can anyone help?

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/vuepress-next/issues/1195
