### ISSUE TITLE
[Bug]在按照教程使用@vuepress/plugin-shiki时报错

### ISSUE THREAD

**Issue by heStudio-Network** [vuepress-theme-hope/vuepress-theme-hope#2860]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### 参照文档
https://theme-hope.vuejs.press/zh/guide/interface/code-theme.html#%E4%BD%BF%E7%94%A8-shiki-%E9%AB%98%E4%BA%AE%E5%99%A8

### 报错截图
![image](https://user-images.githubusercontent.com/119711513/222729975-db0ce640-82c5-4a65-9bfb-012d6ef8aac0.png)

### 报错信息
```text
Error: No language registration for gitignore
    at getGrammar (/workspace/blog-source/node_modules/.pnpm/shiki@0.14.1/node_modules/shiki/dist/index.js:2756:13)
    at codeToThemedTokens (/workspace/blog-source/node_modules/.pnpm/shiki@0.14.1/node_modules/shiki/dist/index.js:2765:26)
    at Object.codeToHtml (/workspace/blog-source/node_modules/.pnpm/shiki@0.14.1/node_modules/shiki/dist/index.js:2783:20)
    at Object.md.options.highlight (file:///workspace/blog-source/node_modules/.pnpm/@vuepress+plugin-shiki@2.0.0-beta.61/node_modules/@vuepress/plugin-shiki/lib/node/shikiPlugin.js:9:60)
    at md.renderer.rules.fence (file:///workspace/blog-source/node_modules/.pnpm/@vuepress+markdown@2.0.0-beta.61/node_modules/@vuepress/markdown/dist/index.js:237:37)
    at n.renderer.rules.fence (file:///workspace/blog-source/node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.186_44bug2q4gvgfsg4b36ccgweufe/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:7:1178)
    at n.renderer.rules.fence (file:///workspace/blog-source/node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.186_44bug2q4gvgfsg4b36ccgweufe/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:7:336)
    at Object.n.renderer.rules.fence (file:///workspace/blog-source/node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.186_44bug2q4gvgfsg4b36ccgweufe/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:15:589)
    at Renderer.render (/workspace/blog-source/node_modules/.pnpm/markdown-it@13.0.1/node_modules/markdown-it/lib/renderer.js:332:38)
    at Renderer.md.renderer.render (file:///workspace/blog-source/node_modules/.pnpm/@mdit-vue+plugin-headers@0.12.0/node_modules/@mdit-vue/plugin-headers/dist/index.mjs:19:12)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Mister-Hope** [comment]
Shiki throws when you want it to highlight a language it doesn't support. If you want further distabout if this behaviour is reasonable or not, go to it's only repo.
