### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'category')

### ISSUE THREAD

**Issue by DreamOfIce** [vuepress-theme-hope/vuepress-theme-hope#2874]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

今天更新到`2.0.0-beta.188`后，运行dev server出错，以下为完整错误：
``` console
PS E:\documents\repo\core-js> npm run docs:dev

> core-js@3.28.0 docs:dev
> npm run --workspace=docs dev


> dev
> vuepress dev

⠸ Initializing and preparing dataerror error in hook onInitialized from vuepress-plugin-blog2
✖ Initializing and preparing data - failed in 1.09s
TypeError: Cannot read properties of undefined (reading 'category')
    at frontmatter (file:///E:/documents/repo/core-js/docs/node_modules/vuepress-theme-hope/lib/node/helpers-57228559.js:11:27813)
    at file:///E:/documents/repo/core-js/node_modules/vuepress-plugin-blog2/lib/node/index.js:14:189
    at Array.map (<anonymous>)
    at O (file:///E:/documents/repo/core-js/node_modules/vuepress-plugin-blog2/lib/node/index.js:13:54)
    at Object.onInitialized [as hook] (file:///E:/documents/repo/core-js/node_modules/vuepress-plugin-blog2/lib/node/index.js:34:729)
    at Object.process (file:///E:/documents/repo/core-js/node_modules/@vuepress/core/dist/index.js:681:37)
    at async appInit (file:///E:/documents/repo/core-js/node_modules/@vuepress/core/dist/index.js:604:3)
    at async file:///E:/documents/repo/core-js/node_modules/@vuepress/cli/dist/index.js:487:7
    at async file:///E:/documents/repo/core-js/node_modules/@vuepress/utils/dist/index.js:106:20
    at async CAC.dev (file:///E:/documents/repo/core-js/node_modules/@vuepress/cli/dist/index.js:486:5)
npm ERR! Lifecycle script `dev` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: corejs-doc
npm ERR!   at location: E:\documents\repo\core-js\docs
```

调试发现，`themeData.locales[localePath]`中没有`blogLocales`，而且配置中也没有对此项进行更改，应该是没有赋默认值
![image](https://user-images.githubusercontent.com/80821706/222966883-4cea767b-33b4-4ec8-8cbf-77e2ed017ea3.png)
查看commit history后，怀疑是此commit的改动：
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/cb7f81c352d990971e0ac2659c01209bad019eea

**Comment by Mister-Hope** [comment]
Thanks for reporting, this is a typo we introduce in performance pr, fixed in 189
