### ISSUE TITLE
[Bug] Failed to resolve import "#ansi-styles" from "node_modules/.pnpm/chalk@5.2.0/node_modules/chalk/source/index.js?v=059a3446". Does the file exist?

### ISSUE THREAD

**Issue by vordimous** [vuepress-theme-hope/vuepress-theme-hope#2961]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

I have updated my blogging [sample repo](https://github.com/vordimous/sample-docs/tree/blog-error) to avoid the need to use the @vuepress/theme-default. Everything works attempting to use the [vuepress-theme-hope](https://github.com/vuepress-theme-hope/vuepress-theme-hope) blog configuration as is.

The below issue occurs when I attempt to [alias](https://github.com/vordimous/sample-docs/blob/blog-error/src/.vuepress/theme/index.ts#L15) the ArticleItem or ArticleList components. I am unsure what is causing the import error as the [replacement components](https://github.com/vordimous/sample-docs/blob/blog-error/src/.vuepress/theme/components/ArticleItem.vue) are very simple.

```
6:18:17 PM [vite] Internal server error: Failed to resolve import "#ansi-styles" from "node_modules/.pnpm/chalk@5.2.0/node_modules/chalk/source/index.js?v=059a3446". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/adanelz/Code/sample-docs/node_modules/.pnpm/chalk@5.2.0/node_modules/chalk/source/index.js?v=059a3446:1:25
  1  |  import ansiStyles from '#ansi-styles';
     |                          ^
  2  |  import supportsColor from '#supports-color';
  3  |  import { // eslint-disable-line import/order
      at formatError (file:///Users/adanelz/Code/sample-docs/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41418:46)
      at TransformContext.error (file:///Users/adanelz/Code/sample-docs/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19)
      at normalizeUrl (file:///Users/adanelz/Code/sample-docs/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39706:33)
      at async TransformContext.transform (file:///Users/adanelz/Code/sample-docs/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39840:47)
      at async Object.transform (file:///Users/adanelz/Code/sample-docs/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///Users/adanelz/Code/sample-docs/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
Failed to resolve import "#ansi-styles" from "node_modules/.pnpm/chalk@5.2.0/node_modules/chalk/source/index.js?v=059a3446". Does the file exist?
```

### Additional context

vuepress info:

```

> blog@1.0.0 info /Users/adanelz/Code/sample-docs
> vuepress info


  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 323.98 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Utilities:
    Git: 2.37.2 - /opt/homebrew/bin/git
  Browsers:
    Chrome: 111.0.5563.110
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.3
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli: 2.0.0-beta.61 => 2.0.0-beta.61 
    @vuepress/client: 2.0.0-beta.61 => 2.0.0-beta.61 
    @vuepress/core: Not Found
    @vuepress/markdown: Not Found
    @vuepress/plugin-active-header-links: Not Found
    @vuepress/plugin-back-to-top: Not Found
    @vuepress/plugin-container: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon: Not Found
    @vuepress/plugin-git: Not Found
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom: Not Found
    @vuepress/plugin-nprogress: Not Found
    @vuepress/plugin-palette: Not Found
    @vuepress/plugin-prismjs: Not Found
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data: Not Found
    @vuepress/plugin-toc: Not Found
    @vuepress/shared: Not Found
    @vuepress/theme-default: Not Found
    @vuepress/utils: 2.0.0-beta.61 => 2.0.0-beta.61 
    vue: 3.2.47 => 3.2.47 
    vue-loader: Not Found
    vue-router: Not Found
    vuepress: Not Found
    vuepress-vite: 2.0.0-beta.61 => 2.0.0-beta.61 
    vuepress-webpack: Not Found

```

**Comment by Mister-Hope** [comment]
Do not import any node side code at client.

**Comment by vordimous** [comment]
> Do not import any node side code at client.

What node package have I pulled in? Everything is client side i believe.

**Comment by Mister-Hope** [comment]
`vuepress-theme-hope` main entry is absolutely a node side one, use `vuepress-theme-hope/client`

**Comment by vordimous** [comment]
Is there a different way to import the typescript types?

**Comment by vordimous** [comment]
The ArticleInfoType enum for the attribute names made the info prop very confusing as a raw js object. I guess I can just copy the enum but if there is a way to import the types that would be ideal.

**Comment by vordimous** [comment]
I confirmed I can just copy the [/packages/theme/src/shared/blog.ts](https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/b62883be297e9339e846e7b25104f03f6888ee84/packages/theme/src/shared/blog.ts) file for now.

```
  import { type ArticleInfo, ArticleInfoType } from "./blog";

  const props = defineProps({
    info: {
      type: Object as PropType<ArticleInfo>,
      required: true,
    },
    path: { type: String, required: true },
  },);
  onMounted(() => {
    console.log(props.info[ArticleInfoType.title]);
  })
```

**Comment by Mister-Hope** [comment]
> The ArticleInfoType enum for the attribute names made the info prop very confusing as a raw js object. I guess I can just copy the enum but if there is a way to import the types that would be ideal. 

The enum is used to make client bundle size smaller. And it's exported both client and node.

**Comment by vordimous** [comment]
I got the dynamic grid format I was looking for by extending the [ArticleList component](https://github.com/vordimous/sample-docs/blob/blog-error/src/.vuepress/theme/components/ArticleList.vue). If you want to check it out, I think it would be a cool addition.

**Comment by vordimous** [comment]
Also thank you for the help and thank you for creating an amazing theme!! You will have some new example sites running in production soon.

https://vordimous.github.io/blog/
https://vordimous.github.io/zilla-docs/
