### ISSUE TITLE
[Bug][vite] Internal server error: Failed to resolve import "@theme-hope/components/CommonWrapper"

### ISSUE THREAD

**Issue by FuckDoctors** [vuepress-theme-hope/vuepress-theme-hope#3067]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

使用 v2.0.0-beta.206 时，无法使用 `@theme-hope/*` 导致无法使用自定义主题和替换组件。
错误信息：

```txt
Failed to resolve import "@theme-hope/components/CommonWrapper" from "docs/.vuepress/client.ts". Does the file exist?
13:53:46 [vite] Internal server error: Failed to resolve import "@theme-hope/components/CommonWrapper" from "docs/.vuepress/client.ts". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/projects/vuepress-theme-hope-k3kxev/docs/.vuepress/client.ts:2:26
  1  |  import { defineClientConfig } from "@vuepress/client";
  2  |  import CommonWrapper from "@theme-hope/components/CommonWrapper";
     |                             ^
  3  |  export default defineClientConfig({
  4  |    // 你可以在这里覆盖或新增布局
      at formatError (file://file:///home/projects/vuepress-theme-hope-k3kxev/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41466:46)
      at TransformContext.error (file://file:///home/projects/vuepress-theme-hope-k3kxev/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41462:19)
      at normalizeUrl (file://file:///home/projects/vuepress-theme-hope-k3kxev/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39754:33)
      at async TransformContext.transform (file://file:///home/projects/vuepress-theme-hope-k3kxev/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39888:47)
      at async Object.transform (file://file:///home/projects/vuepress-theme-hope-k3kxev/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41733:30)
      at async loadAndTransform (file://file:///home/projects/vuepress-theme-hope-k3kxev/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39527:29)
```

最小重现：
https://stackblitz.com/edit/vuepress-theme-hope-k3kxev?file=docs%2F.vuepress%2Fclient.ts

**Comment by Mister-Hope** [comment]
See changelog

**Comment by frg2089** [comment]
[2.0.0-beta.203 changelog](https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/CHANGELOG.md#200-beta203-2023-04-12)

[文档](https://theme-hope.vuejs.press/zh/config/theme/behavior.html#custom)

要不把这个加入到常见问题里吧...
