### ISSUE TITLE
[Bug] Failed to execute the create new project command.

### ISSUE THREAD

**Issue by Sun-ZhenXing** [vuepress-theme-hope/vuepress-theme-hope#3279]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [X] Linux

### Describe the bug

New projects cannot be created by command now.

Error after executing `postinstall`. May be due to the incorrect use of `simple-git-hooks`?

```bash
pnpm create vuepress-theme-hope docs
```

Windows 11: (node: 18.14.0, pnpm: 8.6.6)

```bash
pnpm create vuepress-theme-hope docs
../../../../.pnpm-store/v3/tmp/dlx-22588 |  +72 +++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: D:\.pnpm-store\v3
  Virtual store is at:             ../../../../.pnpm-store/v3/tmp/dlx-22588/node_modules/.pnpm
../../../../.pnpm-store/v3/tmp/dlx-22588 | Progress: resolved 72, reused 72, downloaded 0, added 72, done
? Select a language to display / 选择显示语言 简体中文
? 选择包管理器 pnpm
生成 package.json...
? 设置应用名称 vuepress-theme-hope-template
? 设置应用版本号 2.0.0
? 设置应用描述 A project of vuepress-theme-hope
? 设置协议 MIT
? 项目需要用到多语言么? No
? 是否需要一个自动部署文档到 GitHub Pages 的工作流？ No
? 你想要创建什么类型的项目？ docs
生成模板...
? 是否初始化 Git 仓库? No
安装依赖...
这可能需要数分钟，请耐心等待.
我们无法正确输出子进程的进度条，所以进程可能会看似未响应
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
 WARN  deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
Packages: +763
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: D:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 785, reused 763, downloaded 0, added 763, done
node_modules/.pnpm/@vue+repl@2.5.1/node_modules/@vue/repl: Running postinstall script, failed in 21ms
.../node_modules/@vue/repl postinstall$ simple-git-hooks
│ 'simple-git-hooks' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
│ ���������ļ���
└─ Failed in 22ms at D:\workspace\repo\GraduationDesign\visual-math-docs\docs\node_modules\.pnpm\@vue+repl@2.5.1\node_modules\@vue\repl
 ELIFECYCLE  Command failed with exit code 1.
file:///D:/.pnpm-store/v3/tmp/dlx-22588/node_modules/.pnpm/execa@7.1.1/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: pnpm install
    at makeError (file:///D:/.pnpm-store/v3/tmp/dlx-22588/node_modules/.pnpm/execa@7.1.1/node_modules/execa/lib/error.js:59:11)
    at execaSync (file:///D:/.pnpm-store/v3/tmp/dlx-22588/node_modules/.pnpm/execa@7.1.1/node_modules/execa/index.js:201:17)
    at execaCommandSync (file:///D:/.pnpm-store/v3/tmp/dlx-22588/node_modules/.pnpm/execa@7.1.1/node_modules/execa/index.js:276:9)
    at N (file:///D:/.pnpm-store/v3/tmp/dlx-22588/node_modules/.pnpm/create-vuepress-theme-hope@2.0.0-beta.230/node_modules/create-vuepress-theme-hope/lib/index.js:68:1036)
    at CAC.<anonymous> (file:///D:/.pnpm-store/v3/tmp/dlx-22588/node_modules/.pnpm/create-vuepress-theme-hope@2.0.0-beta.230/node_modules/create-vuepress-theme-hope/lib/index.js:68:1863)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 1: pnpm install',
  command: 'pnpm install',
  escapedCommand: 'pnpm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.14.0
 ERROR  Command failed with exit code 1: create-vuepress-theme-hope docs

pnpm: Command failed with exit code 1: create-vuepress-theme-hope docs
    at makeError (C:\Users\10069\AppData\Local\node\corepack\pnpm\8.6.6\dist\pnpm.cjs:24241:17)
    at handlePromise (C:\Users\10069\AppData\Local\node\corepack\pnpm\8.6.6\dist\pnpm.cjs:24812:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (C:\Users\10069\AppData\Local\node\corepack\pnpm\8.6.6\dist\pnpm.cjs:209241:7)
    at async C:\Users\10069\AppData\Local\node\corepack\pnpm\8.6.6\dist\pnpm.cjs:218647:21
    at async main (C:\Users\10069\AppData\Local\node\corepack\pnpm\8.6.6\dist\pnpm.cjs:218614:34)
    at async runPnpm (C:\Users\10069\AppData\Local\node\corepack\pnpm\8.6.6\dist\pnpm.cjs:218869:5)
    at async C:\Users\10069\AppData\Local\node\corepack\pnpm\8.6.6\dist\pnpm.cjs:218861:7
```

Debian 11: (node: 18.16.0, pnpm: 8.6.6)

```bash
root@29f4bf3badcd:~# pnpm create vuepress-theme-hope docs
.local/share/pnpm/store/v3/tmp/dlx-26    |  +72 +++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.local/share/pnpm/store/v3
  Virtual store is at:             .local/share/pnpm/store/v3/tmp/dlx-26/node_modules/.pnpm
.local/share/pnpm/store/v3/tmp/dlx-26    | Progress: resolved 72, reused 0, downloaded 72, added 72, done
? Select a language to display / 选择显示语言 简体中文
? 选择包管理器 pnpm
生成 package.json...
? 设置应用名称 vuepress-theme-hope-template
? 设置应用版本号 2.0.0
? 设置应用描述 A project of vuepress-theme-hope
? 设置协议 MIT
? 项目需要用到多语言么? No
? 是否需要一个自动部署文档到 GitHub Pages 的工作流？ No
? 你想要创建什么类型的项目？ docs
生成模板...
? 是否初始化 Git 仓库? No
安装依赖...
这可能需要数分钟，请耐心等待.
我们无法正确输出子进程的进度条，所以进程可能会看似未响应
Downloading registry.npmjs.org/dashjs/4.7.1: 7.96 MB/7.96 MB, done
Downloading registry.npmjs.org/echarts/5.4.2: 8.15 MB/8.15 MB, done
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
 WARN  deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
Downloading registry.npmjs.org/mathjax-full/3.2.2: 8.53 MB/8.53 MB, done
Downloading registry.npmjs.org/cytoscape-fcose/2.2.0: 7.6 MB/7.6 MB, done
Packages: +763
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 785, reused 48, downloaded 715, added 763, done
node_modules/.pnpm/@vue+repl@2.5.1/node_modules/@vue/repl: Running postinstall script...
node_modules/.pnpm/core-js@3.31.1/node_modules/core-js: Running postinstall script...
 ELIFECYCLE  Command failed.
node_modules/.pnpm/vue-demi@0.14.5_vue@3.3.4/node_modules/vue-demi: Running postinstall script...
file:///root/.local/share/pnpm/store/v3/tmp/dlx-26/node_modules/.pnpm/execa@7.1.1/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: pnpm install
    at makeError (file:///root/.local/share/pnpm/store/v3/tmp/dlx-26/node_modules/.pnpm/execa@7.1.1/node_modules/execa/lib/error.js:59:11)
    at execaSync (file:///root/.local/share/pnpm/store/v3/tmp/dlx-26/node_modules/.pnpm/execa@7.1.1/node_modules/execa/index.js:201:17)
    at execaCommandSync (file:///root/.local/share/pnpm/store/v3/tmp/dlx-26/node_modules/.pnpm/execa@7.1.1/node_modules/execa/index.js:276:9)
    at N (file:///root/.local/share/pnpm/store/v3/tmp/dlx-26/node_modules/.pnpm/create-vuepress-theme-hope@2.0.0-beta.230/node_modules/create-vuepress-theme-hope/lib/index.js:68:1036)
    at CAC.<anonymous> (file:///root/.local/share/pnpm/store/v3/tmp/dlx-26/node_modules/.pnpm/create-vuepress-theme-hope@2.0.0-beta.230/node_modules/create-vuepress-theme-hope/lib/index.js:68:1863)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 1: pnpm install',
  command: 'pnpm install',
  escapedCommand: 'pnpm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0
 ERROR  Command failed with exit code 1: create-vuepress-theme-hope docs

pnpm: Command failed with exit code 1: create-vuepress-theme-hope docs
    at makeError (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:24241:17)
    at handlePromise (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:24812:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:209241:7)
    at async /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:218647:21
    at async main (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:218614:34)
    at async runPnpm (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:218869:5)
    at async /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:218861:7
```

**Comment by Mister-Hope** [comment]
See https://github.com/vuejs/repl/issues/128

**Comment by Mister-Hope** [comment]
@vue/repl just release v2.5.2, so a new install should work now.
