### ISSUE TITLE
[Bug] 使用vuepress/plugin-shiki插件报错 Error: No language registration for plain     at getGrammar

### ISSUE THREAD

**Issue by lyf110** [vuepress-theme-hope/vuepress-theme-hope#3298]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Error: No language registration for plain
    at getGrammar (G:\Code\Gitee\vuepress2-java-blog\node_modules\.pnpm\shiki@0.14.3\node_modules\shiki\dist\index.js:3043:13)
    at codeToThemedTokens (G:\Code\Gitee\vuepress2-java-blog\node_modules\.pnpm\shiki@0.14.3\node_modules\shiki\dist\index.js:3052:26)
    at Object.codeToHtml (G:\Code\Gitee\vuepress2-java-blog\node_modules\.pnpm\shiki@0.14.3\node_modules\shiki\dist\index.js:3070:20)
    at md.options.highlight (file:///G:/Code/Gitee/vuepress2-java-blog/node_modules/.pnpm/@vuepress+plugin-shiki@2.0.0-beta.66/node_modules/@vuepress/plugin-shiki/lib/node/shikiPlugin.js:9:60)
    at md.renderer.rules.fence (file:///G:/Code/Gitee/vuepress2-java-blog/node_modules/.pnpm/@vuepress+markdown@2.0.0-beta.66/node_modules/@vuepress/markdown/dist/index.js:246:37)
    at r.renderer.rules.fence (file:///G:/Code/Gitee/vuepress2-java-blog/node_modules/.pnpm/@mdit+plugin-tex@0.4.8/node_modules/@mdit/plugin-tex/lib/index.mjs:4:388)
    at n.renderer.rules.fence (file:///G:/Code/Gitee/vuepress2-java-blog/node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.233_vuepress@2.0.0-beta.66/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:11:1178)
    at n.renderer.rules.fence (file:///G:/Code/Gitee/vuepress2-java-blog/node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.233_vuepress@2.0.0-beta.66/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:11:336)
    at n.renderer.rules.fence (file:///G:/Code/Gitee/vuepress2-java-blog/node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.233_vuepress@2.0.0-beta.66/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:23:536)
    at Renderer.render (G:\Code\Gitee\vuepress2-java-blog\node_modules\.pnpm\markdown-it@13.0.1\node_modules\markdown-it\lib\renderer.js:332:38)

**Comment by Mister-Hope** [comment]
shiki Only supports known language highlighting,  So this is expected when you are trying to highlight an unknown language,  And you are expected to customize shiki  To let it support them

**Comment by lmy668** [comment]
i also encount this problem. the error is below.
`Error: No language registration for card
    at getGrammar (E:\develop\dev\my-docs\node_modules\.pnpm\shiki@0.14.3\node_modules\shiki\dist\index.js:3043:13)       
    at codeToThemedTokens (E:\develop\dev\my-docs\node_modules\.pnpm\shiki@0.14.3\node_modules\shiki\dist\index.js:3052:26)
    at Object.codeToHtml (E:\develop\dev\my-docs\node_modules\.pnpm\shiki@0.14.3\node_modules\shiki\dist\index.js:3070:20)    at md.options.highlight (file:///E:/develop/dev/my-docs/node_modules/.pnpm/@vuepress+plugin-shiki@2.0.0-beta.66/node_modules/@vuepress/plugin-shiki/lib/node/shikiPlugin.js:9:60)
    at md.renderer.rules.fence (file:///E:/develop/dev/my-docs/node_modules/.pnpm/@vuepress+markdown@2.0.0-beta.66/node_modules/@vuepress/markdown/dist/index.js:246:37)
    at r.renderer.rules.fence (file:///E:/develop/dev/my-docs/node_modules/.pnpm/@mdit+plugin-tex@0.4.8/node_modules/@mdit/plugin-tex/lib/index.mjs:4:388)
    at n.renderer.rules.fence (file:///E:/develop/dev/my-docs/node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.233_vuepress@2.0.0-beta.66/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:11:1178)
    at n.renderer.rules.fence (file:///E:/develop/dev/my-docs/node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.233_vuepress@2.0.0-beta.66/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:11:336)
    at n.renderer.rules.fence (file:///E:/develop/dev/my-docs/node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.233_vuepress@2.0.0-beta.66/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:23:536)
    at Renderer.render (E:\develop\dev\my-docs\node_modules\.pnpm\markdown-it@13.0.1\node_modules\markdown-it\lib\renderer.js:332:38)`
