### ISSUE TITLE
[Bug] ERROR: No loader is configured for ".vue" files

### ISSUE THREAD

**Issue by herodotus-cloud** [vuepress-theme-hope/vuepress-theme-hope#3788]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

# 环境 
- vuepress-hope-theme 2.0.0-rc4
- node v20.10.0

# 代码依赖

```json
  "devDependencies": {
    "@types/node": "^20.10.5",
    "@vue/repl": "^3.1.0",
    "@vuepress/client": "2.0.0-rc.0",
    "@vuepress/utils": "2.0.0-rc.0",
    "chart.js": "^4.4.1",
    "commitizen": "^4.3.0",
    "cz-conventional-changelog": "^3.3.0",
    "echarts": "^5.4.3",
    "flowchart.ts": "^2.0.0",
    "husky": "^8.0.3",
    "katex": "^0.16.9",
    "lint-staged": "^15.2.0",
    "mathjax-full": "^3.2.2",
    "mermaid": "^10.6.1",
    "prettier": "^3.1.1",
    "reveal.js": "^5.0.4",
    "vue": "^3.3.13",
    "vuepress": "2.0.0-rc.0",
    "vuepress-theme-hope": "2.0.0-rc.4"
  }
```

# 问题描述

代码中，有三个自己定义的“替换主题的组件”。

## 下面是其中的一个代码：

```js
<template>
  <Sidebar>
    <template #top>
      <template v-if="isDisplayPlatinum">
        <a v-for="item in platinum" :href="item.href" target="_blank">
          <img
            :src="item.imgSrc"
            :alt="item.imgAlt"
            class="no-zoom"
            style="width: 95%; border-radius: 2px; margin-left: 8px"
          />
        </a>
      </template>
    </template>
  </Sidebar>
</template>
<script lang="ts">
import { defineComponent, ref, computed } from "vue";

import Sidebar from "vuepress-theme-hope/modules/sidebar/components/Sidebar.js";

import { useSponsor } from "./hooks";

export default defineComponent({
  name: "HerodotusNormalPage",

  components: {
    Sidebar,
  },

  setup() {
    const { platinum, isDisplayPlatinum } = useSponsor();

    return { platinum, isDisplayPlatinum };
  },
});
</script>

```
## 配置

```json

 alias: {
    "@theme-hope/components/HomePage": path.resolve(
      __dirname,
      "./components/HomePage.vue"
    ),
    "@theme-hope/components/NormalPage": path.resolve(
      __dirname,
      "./components/NormalPage.vue"
    ),
    "@theme-hope/modules/sidebar/components/Sidebar": path.resolve(
      __dirname,
      "./components/Sidebar.vue"
    ),
  },
```

## 说明

这几个组件，使用 vuepress-theme-hope 2.0.0-rc.4 及以前的版本，均运行正常。

将 vuepress-theme-hope 升级至 2.0.0-rc.5 或者 2.0.0-rc.6以后，使用 `pnpm docs:dev` 本地运行，就会出现页面无法显示，浏览器中都是空白，控制台会抛出以下错误：

```shell
X [ERROR] No loader is configured for ".vue" files: src/.vuepress/components/HomePage.vue

    node_modules/.pnpm/vuepress-theme-hope@2.0.0-rc.6_@vue+repl@3.1.0_chart.js@4.4.1_echarts@5.4.3_flowchart.ts@2.0._ozeipyvmfn3pxsx5nwhkimpbkm/node_modules/vuepress-theme-hope/lib/client/layouts/Layout.js:4:21:
      4 │ import HomePage from "@theme-hope/components/HomePage";
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] No loader is configured for ".vue" files: src/.vuepress/components/NormalPage.vue

    node_modules/.pnpm/vuepress-theme-hope@2.0.0-rc.6_@vue+repl@3.1.0_chart.js@4.4.1_echarts@5.4.3_flowchart.ts@2.0._ozeipyvmfn3pxsx5nwhkimpbkm/node_modules/vuepress-theme-hope/lib/client/layouts/Layout.js:5:23:
      5 │ import NormalPage from "@theme-hope/components/NormalPage";
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] No loader is configured for ".vue" files: src/.vuepress/components/Sidebar.vue

    node_modules/.pnpm/vuepress-theme-hope@2.0.0-rc.6_@vue+repl@3.1.0_chart.js@4.4.1_echarts@5.4.3_flowchart.ts@2.0._ozeipyvmfn3pxsx5nwhkimpbkm/node_modules/vuepress-theme-hope/lib/client/components/CommonWrapper.js:9:20:
      9 │ import Sidebar from "@theme-hope/modules/sidebar/components/Sidebar";
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

17:10:27 [vite] error while updating dependencies:
Error: Build failed with 3 errors:
node_modules/.pnpm/vuepress-theme-hope@2.0.0-rc.6_@vue+repl@3.1.0_chart.js@4.4.1_echarts@5.4.3_flowchart.ts@2.0._ozeipyvmfn3pxsx5nwhkimpbkm/node_modules/vuepress-theme-hope/lib/client/components/CommonWrapper.js:9:20: ERROR: No loader is configured for ".vue" files: src/.vuepress/components/Sidebar.vue
node_modules/.pnpm/vuepress-theme-hope@2.0.0-rc.6_@vue+repl@3.1.0_chart.js@4.4.1_echarts@5.4.3_flowchart.ts@2.0._ozeipyvmfn3pxsx5nwhkimpbkm/node_modules/vuepress-theme-hope/lib/client/layouts/Layout.js:4:21: ERROR: No loader is configured for ".vue" files: src/.vuepress/components/HomePage.vue
node_modules/.pnpm/vuepress-theme-hope@2.0.0-rc.6_@vue+repl@3.1.0_chart.js@4.4.1_echarts@5.4.3_flowchart.ts@2.0._ozeipyvmfn3pxsx5nwhkimpbkm/node_modules/vuepress-theme-hope/lib/client/layouts/Layout.js:5:23: ERROR: No loader is configured for ".vue" files: src/.vuepress/components/NormalPage.vue
    at failureErrorWithLog (D:\workspaces\Develop\dante-cloud-docs\node_modules\.pnpm\esbuild@0.19.10\node_modules\esbuild\lib\main.js:1650:15)
    at D:\workspaces\Develop\dante-cloud-docs\node_modules\.pnpm\esbuild@0.19.10\node_modules\esbuild\lib\main.js:1058:25
    at D:\workspaces\Develop\dante-cloud-docs\node_modules\.pnpm\esbuild@0.19.10\node_modules\esbuild\lib\main.js:1526:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

退回至 vuepress-hope-theme 2.0.0-rc4，又恢复正常，不会出现任何错误。

**Comment by Mister-Hope** [comment]
#3770
