### ISSUE TITLE
[Bug] 新增图片不支持热更新

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress-theme-hope/vuepress-theme-hope#3937]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

图片不支持热更新了，每次添加新的图片需要重启服务。

很久没有添加过图片了，不知道是什么时候开始的，今天突然发现无法热更新。

```
vite：5.1.3
node：20.11.19
vuepress：2.0.0-rc.7
vuepress-theme-hope: 2.0.0-rc.24
```

### Additional context

```
14:19:29 [vite] Internal server error: Failed to resolve import "/images/指南/开发环境/代码版本管理/鼠标右键面板-合并分支.png" from "docs/.vuepress/.temp/pages/guide/dev-env/代码版本管理.html.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/Web Workspace/CODE_Develop/Service_Products/BasicPaper/webCode/basic-paper-cloud-vue3/docs/.vuepress/.temp/pages/guide/dev-env/代码版本管理.html.vue:6:25
  4  |  import _imports_1 from '/images/指南/开发环境/代码版本管理/创建版本分支.png'
  5  |  import _imports_2 from '/images/指南/开发环境/代码版本管理/分支列表.png'
  6  |  import _imports_3 from '/images/指南/开发环境/代码版本管理/鼠标右键面板-合并分支.png'
     |                          ^
  7  |
  8  |
      at formatError (file:///D:/Web%20Workspace/CODE_Develop/Service_Products/BasicPaper/webCode/basic-paper-cloud-vue3/node_modules/.pnpm/vite@5.1.3_@types+node@20.11.19_less@4.2.0_sass@1.71.0/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:50500:46)
      at TransformContext.error (file:///D:/Web%20Workspace/CODE_Develop/Service_Products/BasicPaper/webCode/basic-paper-cloud-vue3/node_modules/.pnpm/vite@5.1.3_@types+node@20.11.19_less@4.2.0_sass@1.71.0/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:50494:19)
      at normalizeUrl (file:///D:/Web%20Workspace/CODE_Develop/Service_Products/BasicPaper/webCode/basic-paper-cloud-vue3/node_modules/.pnpm/vite@5.1.3_@types+node@20.11.19_less@4.2.0_sass@1.71.0/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:65562:33)
      at async file:///D:/Web%20Workspace/CODE_Develop/Service_Products/BasicPaper/webCode/basic-paper-cloud-vue3/node_modules/.pnpm/vite@5.1.3_@types+node@20.11.19_less@4.2.0_sass@1.71.0/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:65717:47
      at async Promise.all (index 4)
      at async TransformContext.transform (file:///D:/Web%20Workspace/CODE_Develop/Service_Products/BasicPaper/webCode/basic-paper-cloud-vue3/node_modules/.pnpm/vite@5.1.3_@types+node@20.11.19_less@4.2.0_sass@1.71.0/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:65638:13)
      at async Object.transform (file:///D:/Web%20Workspace/CODE_Develop/Service_Products/BasicPaper/webCode/basic-paper-cloud-vue3/node_modules/.pnpm/vite@5.1.3_@types+node@20.11.19_less@4.2.0_sass@1.71.0/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:50809:30)
      at async loadAndTransform (file:///D:/Web%20Workspace/CODE_Develop/Service_Products/BasicPaper/webCode/basic-paper-cloud-vue3/node_modules/.pnpm/vite@5.1.3_@types+node@20.11.19_less@4.2.0_sass@1.71.0/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:53582:29)
      at async viteTransformMiddleware (file:///D:/Web%20Workspace/CODE_Develop/Service_Products/BasicPaper/webCode/basic-paper-cloud-vue3/node_modules/.pnpm/vite@5.1.3_@types+node@20.11.19_less@4.2.0_sass@1.71.0/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:63377:32)
14:19:29 [vite] Pre-transform error: Failed to resolve import "/images/指南/开发环境/代码版本管理/鼠标右键面板-合并分支.png" from "docs/.vuepress/.temp/pages/guide/dev-env/代码版本管理.html.vue". Does the file exist?

```

**Comment by Mister-Hope** [comment]
@meteorlxy

**Comment by Mister-Hope** [comment]
Can you open an issue at https://github.com/vuepress/core?

**Comment by WangJincheng4869** [comment]
> Can you open an issue at https://github.com/vuepress/core?

可以，我抽空搞一下
