### ISSUE TITLE
[Bug] CN sidebar raises error | 配置中文侧边栏时出现报错

### ISSUE THREAD

**Issue by CanYing0913** [vuepress-theme-hope/vuepress-theme-hope#4319]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

中文文件都在`src/.vuepress/zh/posts/`目录下，配置中文侧边栏时：
```
export const zhSidebar = sidebar({
  "/zh/": [
    "",
    {
      text: "关于我",
      icon: "face-smile",
      link: "/zh/intro.html",
    },
    {
      text: "学术",
      icon: "laptop-code",
      prefix: "/zh/posts/01.学术/",
      link: "/zh/posts/01.学术/",
      children: "structure",
      collapsible: true
    },
  ],
});
```
出现报错：
```
Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at Pe (webpack-internal:///./node_modules/vuepress-theme-hope/lib/bundle/SkipLink-T9HOcX0R.js:38:5341)
    at eval (webpack-internal:///./node_modules/vuepress-theme-hope/lib/bundle/SkipLink-T9HOcX0R.js:38:5410)
    at Proxy.map (<anonymous>)
    at me (webpack-internal:///./node_modules/vuepress-theme-hope/lib/bundle/SkipLink-T9HOcX0R.js:38:5403)
    at Ua (webpack-internal:///./node_modules/vuepress-theme-hope/lib/bundle/SkipLink-T9HOcX0R.js:38:5692)
    at Ya (webpack-internal:///./node_modules/vuepress-theme-hope/lib/bundle/SkipLink-T9HOcX0R.js:38:6244)
    at eval (webpack-internal:///./node_modules/vuepress-theme-hope/lib/bundle/SkipLink-T9HOcX0R.js:38:6866)
    at ReactiveEffect.eval [as fn] (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:1042:13)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:221:19)
    at get value (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:1054:147)
```
经测试，一旦prefix不为`""`，则此问题会出现。将其设置为空字符串时，有一个很奇怪的现象：
```
{
      text: "学术",
      icon: "laptop-code",
      // prefix: "/zh/posts/",
      link: "/zh/posts/01.学术/",
      children: "structure",
      collapsible: true
    },
```
![QQ_1723107467829](https://github.com/user-attachments/assets/65f420e6-09f7-4473-a9e3-164f3578f723)
可以看到它把整个网站的structure都列出来了。英文侧边栏则没有这个问题。

**Comment by CanYing0913** [comment]
已解决：去掉中文侧边栏`prefix`中的`/zh/`前缀
