### ISSUE TITLE
[Bug] Structure rendering and readme.md not parsed properly

### ISSUE THREAD

**Issue by robertraaijmakers** [vuepress-theme-hope/vuepress-theme-hope#4351]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

When using the "structure" for sidebar rendering the readme.md is parsed differently. When dir.text is not used, the text displayed is the file path instead of the title frontmatter attribute specified in the readme.md

readme.md frontmatter definition
```
---
title: Power Platform Setup
author: Jane Doe
dir:
 order: 1
---
```

<img width="244" alt="image" src="https://github.com/user-attachments/assets/d78fabff-e4c2-400d-8476-8e55f5645f29">

If more information is needed then I would gladly help to specify. I really like this structure feature and options available!!

**Comment by Mister-Hope** [comment]
The special name for markdown files should be `README`, and I think that at least `README.md` should work as expected, and  I might only handle that file with structured sidebar.

But we could treat this as a bug, and see if we can make a better support.

**Comment by robertraaijmakers** [comment]
Thanks, I think the issue was that I named it readme.md with small letters. But very happy to see that index.md support is now added! 👍

**Comment by robertraaijmakers** [comment]
Hi, quick question (for internal stakeholder management on my side), when can we expect this fix to be pushed as new RC? Thanks and have a good weekend!

**Comment by Mister-Hope** [comment]
I'm busy these days and I'm trying to follow the guidelines which introduced in the ecosystem in the latest rc version

**Comment by Mister-Hope** [comment]
So it will be a couple of days for a new a rc version to be landed.

**Comment by wilcoblom** [comment]
We are having this issue as well, any idea when we can expect this fix?

**Comment by Mister-Hope** [comment]
I am on a trip and facing typhoon now, I can not create a new release at least in the comming 10 days. The new version should have some new adjustments based on upstream changes, so please be patient.

**Comment by wilcoblom** [comment]
I hope you got back home safely @Mister-Hope.... 
Can you already say anything yet about when we can expect the update? Thanks in advance!

**Comment by Mister-Hope** [comment]
I was working on with other things that needs to be brought with the new version at `work` branch, and you can see that I am continue working on it, while some of the cis are failing, I will probably release a new version before 9/20.

**Comment by Mister-Hope** [comment]
For the process, you should check https://github.com/vuepress-theme-hope/vuepress-theme-hope/pull/4453

**Comment by robertraaijmakers** [comment]
Hi @Mister-Hope,

Thanks for merging and publishing this fix and sorry to bother again.

I have tried upgrading to RC56, after fixing some breaking changes in the config the site compiles and runs again. However, the index.md files are still not picked up correctly. If I change one of my index files to README.md it renders properly. I checked the main branch and the fix all seems to be in there, so don't know why exactly it is not working properly.

Next to that, with upgrading to RC56, the theme color doesn't seem to be found anymore. In palette.scss I have specified a theme color and that was working as exepected, however, after the upgrade all links and layout options have the default color again.

I then saw that a new version (RC57) is already available, so tried upgrading to that version. However then I get another error when compiling:
```
error TypeError: Cannot read properties of undefined (reading 'components')
    at Da (file:///C:/Proj/node_modules/vuepress-theme-hope/lib/node/index.js:3:4590)
    at Oe (file:///C:/Proj/node_modules/vuepress-theme-hope/lib/node/index.js:3:6506)
    at file:///C:/Proj/node_modules/vuepress-theme-hope/lib/node/index.js:124:218
    at resolvePluginObject (file:///C:/Proj/node_modules/@vuepress/core/dist/index.js:616:65)
    at resolveThemeInfo (file:///C:/Proj/node_modules/@vuepress/core/dist/index.js:909:23)
    at setupAppThemeAndPlugins (file:///C:/Proj/node_modules/@vuepress/core/dist/index.js:930:21)
    at createBaseApp (file:///C:/Proj/node_modules/@vuepress/core/dist/index.js:960:3)
    at createDevApp (file:///C:/Proj/node_modules/@vuepress/core/dist/index.js:974:15)
    at CAC.dev (file:///C:/Proj/node_modules/@vuepress/cli/dist/index.js:457:17)
```

Did I miss some config change why something is now undefined? I have the components specified in theme.ts (just like before). Do I need to change something there?
```
    components: {
      components: ["Badge", "VPCard"],
    },
```

Hope you can help :)

**Comment by Mister-Hope** [comment]
This is an isssue, and it's fixed in rc 58
