### ISSUE TITLE
[Bug] 2.0.0-rc.60 [vite] Pre-transform error: [sass] Error: Can't find stylesheet to import

### ISSUE THREAD

**Issue by AdamBearWA** [vuepress-theme-hope/vuepress-theme-hope#4616]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

New default 2.0.0-rc.60 builds but does not run. There is a runtime error as soon as you load http://localhost:8080 in a browser.

```
PS C:\repos> npm init vuepress-theme-hope@latest testdocs

> npx
> create-vuepress-theme-hope testdocs

✔ Select a language to display / 选择显示语言 English
✔ Choose package manager npm
✔ Which bundler do you want to use? vite
Generating package.json...
✔ Your project name project-name
✔ Your project description Project description
✔ Your project version 1.0.0
✔ Your project license MIT
Generating tsconfig.json...
✔ What type of project do you want to create? docs
✔ Does the project need multiple languages? no
Generating Template...
✔ Initialize a git repository? yes
✔ Do you need a GitHub workflow to deploy docs on GitHub pages? no
Installing Deps...
This may take a few minutes, please be patient.
We can not correctly output progress bar from child process, so the process may look stuck.

added 385 packages, and audited 386 packages in 1m

104 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Successful Generated!
✔ Would you like to preview template now? no
Hint: You should execute "npm run docs:dev" to start dev server.PS C:\repos> cd testdocs
PS C:\repos\testdocs> npm run docs:dev

> project-name@1.0.0 docs:dev
> vuepress-vite dev src

✔ Initializing and preparing data - done in 3.65s

  vite v5.4.11 dev server running at:

  ➜  Local:   http://localhost:8080/
  ➜  Network: http://192.168.xxx.xxx:8080/
  ➜  Network: http://172.xxx.xxx.xxx:8080/
11:47:01 am [vite] Pre-transform error: [sass] Error: Can't find stylesheet to import.
   ╷
19 │ @use "footer";
   │ ^^^^^^^^^^^^^
   ╵
  ..\..\..\vuepress-theme-hope\lib\bundle\styles\all.scss 19:1  root stylesheet
11:47:01 am [vite] Internal server error: [sass] Error: Can't find stylesheet to import.
   ╷
19 │ @use "footer";
   │ ^^^^^^^^^^^^^
   ╵
  ..\..\..\vuepress-theme-hope\lib\bundle\styles\all.scss 19:1  root stylesheet
  Plugin: vite:css
  File: C:/repos/testdocs/node_modules/vuepress-theme-hope/lib/bundle/styles/all.scss
      at handleCompileResponse (C:\repos\testdocs\node_modules\sass-embedded\dist\lib\src\compiler\utils.js:155:15)
      at AsyncCompiler.compileRequestAsync (C:\repos\testdocs\node_modules\sass-embedded\dist\lib\src\compiler\async.js:100:54)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.compileStringAsync (C:\repos\testdocs\node_modules\sass-embedded\dist\lib\src\compile.js:45:16)
      at async FakeWorker.eval [as _fn] (eval at FakeWorker (file:///C:/repos/testdocs/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:19645:16), <anonymous>:41:22)
      at async FakeWorker.run (file:///C:/repos/testdocs/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:19649:14)
      at async process (file:///C:/repos/testdocs/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:37577:24)
      at async compileCSSPreprocessors (file:///C:/repos/testdocs/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:36741:28)
      at async compileCSS (file:///C:/repos/testdocs/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:36795:32)
      at async TransformPluginContext.transform (file:///C:/repos/testdocs/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:36170:11)
```

**Comment by Mister-Hope** [comment]
Thanks for reporting https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/49d1c97857805025741a3eaec166bb20acbc13d7
