### ISSUE TITLE
[Bug] <ArticleItem> info 对象中的某些属性为 undefined 或不存在

### ISSUE THREAD

**Issue by pysio2007** [vuepress-theme-hope/vuepress-theme-hope#4624]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

在更新到RC.63之后 遇到了此问题

源代码库： https://github.com/PysioHub/Vue-blog-Dev
相关提交： https://github.com/pysio2007/Vue-blog/pull/223/commits/e68605aa0025935a9be57e035784e014da4134a2
```

⠦ Rendering pages /intro.html[Vue warn]: Unhandled error during execution of render function 
  at <ArticleItem key="/posts/develop/Blog%20Architecture.html" info= {
  d: 1732419898000,
  c: 'develop',
  g: [ '博客开发' ],
  e: '<h2>主站框架</h2>\n' +
    '<p>使用框架 <a href="https://github.com/vuepress-theme-hope/vuepress-theme-hope/" target="_blank" rel="noopener noreferrer">Vuepress-Theme-Hope</a></p>\n' +
    '<h2>图片/头像/字体 分发</h2>\n' +
    '<p>所有文件使用 <a href="https://github.com/SaltWood-Studio/Open93AtHome-V3" target="_blank" rel="noopener noreferrer">Open93AtHome</a> 分发</p>',
  r: { minutes: 0.55, words: 164 },
  t: '博客目前的架构',
  i: 'fa-solid fa-screwdriver-wrench',
  y: 'a'
} path="/posts/develop/Blog%20Architecture.html" > 
  at <BaseTransition onAppear=fn onAfterAppear=fn<n2> onEnter=fn  ... > 
  at <Transition name="drop" appear=true onAppear=fn<l2>  ... > 
  at <DropTransition appear=true delay=0 >
  at <ArticleList items= [
  {
    path: '/posts/develop/Blog%20Architecture.html',
    info: {
      d: 1732419898000,
      c: 'develop',
      g: [Array],
      e: '<h2>主站框架</h2>\n' +
        '<p>使用框架 <a href="https://github.com/vuepress-theme-hope/vuepress-theme-hope/" target="_blank" rel="noopener noreferrer">Vuepress-Theme-Hope</a></p>\n' +
        '<h2>图片/头像/字体 分发</h2>\n' +
        '<p>所有文件使用 <a href="https://github.com/SaltWood-Studio/Open93AtHome-V3" target="_blank" rel="noopener noreferrer">Open93AtHome</a> 分发</p>',
      r: [Object],
      t: '博客目前的架构',
      i: 'fa-solid fa-screwdriver-wrench',
      y: 'a'
    }
  },
  {
    path: '/posts/develop/randomimage.html',
    info: {
      d: 1730924695000,
      c: 'develop',
      g: [Array],
      e: '<p>本站现在提供了一个随机图片的API 你可以直接使用下面的URL获取一张随机图片</p>\n' +
        '<div class="language-url" data-highlighter="prismjs" data-ext="url" data-title="url"><pre><code><span class="line"><span class="token scheme">https<span class="token scheme-delimiter">:</span></span><span class="token authority"><span class="token authority-delimiter">//</span><span class="token host">blogapi.pysio.online</span></span><span class="token path"><span class="token path-separator">/</span>random_image</span></span>\n' +
        '<span class="line"></span></code></pre>\n' +
        '</div>',
      r: [Object],
      t: '随机图片API',
      i: 'fa-solid fa-image',
      y: 'a'
    }
  },
  {
    path: '/posts/develop/icon.html',
    info: {
      d: 1730440519000,
      c: 'develop',
      g: [Array],
      e: '<h2>使用</h2>\n' +
        '<p>你可以直接引用以下JS文件来使用本博客自定义的FontAwesome</p>\n' +
        '<div class="language-javascript" data-highlighter="prismjs" data-ext="js" data-title="js"><pre><code><span class="line"><span class="token operator">&lt;</span>script src<span class="token operator">=</span><span class="token string">"https://files.pysio.online/files/Pysio-FontAwesome/js/custom-icons.js"</span> crossorigin<span class="token operator">=</span><span class="token string">"anonymous"</span><span class="token operator">&gt;</span><span class="token operator">&lt;</span><span class="token operator">/</span>script<span class="token operator">&gt;</span></span>\n' +
        '<span class="line"></span></code></pre>\n' +
        '</div>',
      r: [Object],
      t: '本博客自定义的FontAwesome',
      i: 'fa-solid fa-font-awesome',
      y: 'a'
    }
  },
  {
    path: '/posts/daily/WordPress%20to%20VuePress.html',
    info: {
      d: 1729482482000,
      c: 'daily',
      g: [Array],
      e: '<h2>开篇 为什么要迁移？</h2>\n' +
        '<p>在过去的1年多 我都使用WordPress 作为我的博客系统，但是我手上的小鸡实在是太弱了，实在是带不动WordPress这个大家伙，所以我决定迁移到VuePress上来。</p>\n' +
        '<h2>开始迁移</h2>\n' +
        '<p>最开始 我看了很多静态资源生成系统，比如Hexo、Hugo、Jekyll，最后我选择了<a href="https://theme-hope.vuejs.press/" target="_blank" rel="noopener noreferrer">VuePress Theme Hope</a>。</p>\n' +
        '<p>那么开始迁移吧！</p>',
      r: [Object],
      t: '从WordPress迁移到VuePress',
      i: 'fa-brands fa-vuejs',
      y: 'a'
    }
  },
  {
    path: '/posts/NekoXii/Crazy.html',
    info: {
      a: 'NekoXii',
      d: 1729397568000,
      c: 'NekoXii',
      g: [Array],
      e: '<p>你҉҉҈ 要҉҉҈ 永҉҉҈ 远҉҉҈ 爱҉҉҈ 我҉҉҈ 啊</p>\n',
      r: [Object],
      t: '狠狠的石健你们',
      i: 'fa-regular fa-heart',
      y: 'a'
    }
  },
  {
    path: '/posts/daily/HuoShen80Hub.html',
    info: {
      d: 1728598332000,
      c: 'daily',
      g: [Array],
      e: '<!-- markdownlint-disable MD028 -->\n' +
        '<div class="hint-container info">\n' +
        '<p class="hint-container-title">相关信息</p>\n' +
        '<p>这里会展示火神80群里的梗图</p>\n' +
        '</div>\n' +
        '<!-- markdownlint-enable MD028 -->\n',
      r: [Object],
      t: '火神80群里的梗图',
      i: 'fa-regular fa-image',
      y: 'a'
    }
  },
  {
    path: '/posts/daily/PWA.html',
    info: {
      d: 1728415507000,
      g: [Array],
      e: '<!-- markdownlint-disable MD028 -->\n' +
        '<!-- > [!warning] \n' +
        '> 因为目前在快速迭代中，PWA暂时关闭，等待后续开发完成后再开启。  -->\n' +
        '<div class="hint-container info">\n' +
        '<p class="hint-container-title">相关信息</p>\n' +
        '<p>渐进式网络应用程序（英语：Progressive Web Apps，简称：PWA）是一种普通网页或网站架构起来的网络应用程序，但它可以以传统应用程序或原生移动应用程序形式展示给用户。这种应用程序形态视图将目前最为现代化的浏览器提供的功能与移动设备的体验 优势相结合。</p>\n' +
        '</div>',
      r: [Object],
      t: '有关于本博客的PWA',
      i: 'fa-kit fa-pwa fa-xs',
      y: 'a'
    }
  },
  {
    path: '/posts/develop/OpenMCIM.html',
    info: {
      d: 1728307940000,
      c: 'develop',
      g: [Array],
      e: '<!-- markdownlint-disable MD028 -->\n' +
        '<div class="hint-container info">\n' +
        '<p class="hint-container-title">相关信息</p>\n' +
        '<p>MCIM 需要提供文件镜像，但由于成本问题，以及受到 OpenBMCLAPI 的启发，本项目分发 Mod 文件基于网盘\n' +
        '感谢各位的支持~！感谢您为改善国内 Mod 下载环境的贡献！</p>\n' +
        '</div>\n' +
        '<!-- markdownlint-enable MD028 -->\n',
      r: [Object],
      t: '部署OpenMcim节点',
      i: 'fa-kit fa-modrinth',
      y: 'a'
    }
  },
  {
    path: '/posts/develop/Public%20DNS%20DOH.html',
    info: {
      d: 1728146831000,
      c: 'develop',
      g: [Array],
      e: '<p>注意 如果你滥用DNS 则可能导致你的IP地址被封禁</p>\n' +
        '<div class="language-text" data-highlighter="prismjs" data-ext="text" data-title="text"><pre><code><span class="line"></span>\n' +
        '<span class="line">DNS Server ：101.43.154.197</span>\n' +
        '<span class="line"></span>\n' +
        '<span class="line">DoH（中国大陆）: https://doh.pysio.online/dns-query</span>\n' +
        '<span class="line"></span>\n' +
        '<span class="line">DoT（中国大陆）：tls://doh.pysio.online:853</span>\n' +
        '<span class="line"></span>\n' +
        '<span class="line">DoH (非中国大陆 Cloudflare): https://dohk.pysio.online/dns-query</span>\n' +
        '<span class="line"></span>\n' +
        '<span class="line"></span></code></pre>\n' +
        '</div>',
      r: [Object],
      t: '公共DNS/DOH服务',
      i: 'fa-regular fa-server',
      y: 'a'
    }
  },
  {
    path: '/posts/daily/Destiny%20Year7.html',
    info: {
      d: 1728146831000,
      c: 'daily',
      g: [Array],
      e: '<p>这几天打年7打的脑子疼，凯德活了 但是没有完全活，最后还是死了。</p>\n' +
        '<p>8号凌晨1点开的Dayone 打了，6小时才过老一 直接向见证者投降，太难了。</p>\n' +
        '<p>截至发文时，目前只有1队通关</p>\n' +
        '<p>不多说了 放点截图</p>\n',
      r: [Object],
      t: '命运2 年7',
      i: 'fa-kit fa-destiny2',
      y: 'a'
    }
  },
  {
    path: '/posts/daily/Gitlab%20Pollution.html',
    info: {
      d: 1728146831000,
      g: [Array],
      e: '<p>我今天闲的一Ping\n' +
        '<img src="https://files.pysio.online/files/Pysio-Imges/20241006004058.png" alt="" loading="lazy"></p>\n' +
        '<p>我就在纳闷了，为啥会解析到这个<a href="https://106.74.25.198/" target="_blank" rel="noopener noreferrer">IP</a>上，直到我一访问。\n' +
        '<img src="https://files.pysio.online/files/Pysio-Imges/20241006004137.png" alt="" loading="lazy"></p>',
      r: [Object],
      t: '有关于自托管Gitlab被拦截这件事',
      i: 'fa-brands fa-gitlab',
      y: 'a'
    }
  },
  {
    path: '/posts/develop/1Panel%20Redis%20Object%20Cache.html',
    info: {
      d: 1728138165000,
      c: 'develop',
      g: [Array],
      e: '<h2>第一步 获取Redis的密码</h2>\n' +
        '<p><img src="https://files.pysio.online/files/Pysio-Imges/20241005215409.png" alt="" loading="lazy">\n' +
        '[应用商店] -&gt; [已安装] -&gt; [Redis 参数] 就可以看见密码了 把密码记下来</p>\n' +
        '<h2>第二步 修改object-cache.php文件</h2>\n' +
        '<p>在网站根目录 <code>wp-content/plugins/redis-cache/includes</code> 下 可以找到 <code>object-cache.php</code> 文件\n' +
        '打开并编辑<br>\n' +
        '<img src="https://files.pysio.online/files/Pysio-Imges/20241005215426.png" alt="" loading="lazy"><br>\n' +
        '添加或修改以下部分 其中PassWord是你刚刚获取的Redis密码</p>',
      r: [Object],
      t: '1panel面板配置Redis Object Cache插件',
      i: 'fa-brands fa-wordpress',
      y: 'a'
    }
  },
  {
    path: '/posts/develop/Enabling%20the%20xterm.js%20console%20for%20OpenSuse%20in%20PVE%20.html',
    info: {
      d: 1728138165000,
      c: 'develop',
      g: [Array],
      e: '<h2>关闭 VM，并给 VM 添加一个 serial port</h2>\n' +
        '<p>在 PVE Host 中用 qm 命令建立 serial port，假设我的 VM ID 是 100</p>\n' +
        '<div class="language-bash" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre><code><span class="line">qm <span class="token builtin class-name">set</span> <span class="token number">100</span> <span class="token parameter variable">-serial0</span> socket</span>\n' +
        '<span class="line"></span></code></pre>\n' +
        '</div>',
      r: [Object],
      t: '在PVE为OpenSuse启用xterm.js控制台',
      i: 'fa-brands fa-opensuse',
      y: 'a'
    }
  },
  {
    path: '/posts/develop/Remove%20Pve%20No%20valid%20subscription.html',
    info: {
      d: 1728138165000,
      c: 'develop',
      g: [Array],
      e: '<p>修改 <code>/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js</code> 将</p>\n' +
        '<div class="language-javascript" data-highlighter="prismjs" data-ext="js" data-title="js"><pre><code><span class="line">Ext<span class="token punctuation">.</span>Msg<span class="token punctuation">.</span><span class="token function">show</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>\n' +
        '<span class="line"></span></code></pre>\n' +
        '</div>',
      r: [Object],
      t: '去除 PVE “无有效的订阅” 弹窗',
      i: 'fa-kit fa-pve',
      y: 'a'
    }
  },
  {
    path: '/posts/daily/OpenBmclapi.html',
    info: {
      d: 1728106839000,
      c: 'daily',
      g: [Array],
      e: '<p>搭建这玩意也是一时兴起，想想也该给免费的镜像服务贡献点自己的力量。</p>\n' +
        '<p>网盘节点地址：https://65d480a1f25ffe347bdf6820.openbmclapi.933.moe/</p>\n',
      r: [Object],
      t: 'OpenBmclapi',
      i: 'fa-solid fa-cloud',
      y: 'a'
    }
  },
  {
    path: '/posts/develop/Manual%20merge%20Pull%20requests.html',
    info: {
      d: 1727995365000,
      c: 'develop',
      g: [Array],
      e: '<p>首先 通过命令添加远程的仓库信息</p>\n' +
        '<div class="language-bash" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre><code><span class="line"><span class="token function">git</span> remote <span class="token function">add</span> <span class="token punctuation">[</span>远程仓库名称<span class="token punctuation">]</span> <span class="token punctuation">[</span>远程仓库地址<span class="token punctuation">]</span> </span>\n' +
        '<span class="line"></span></code></pre>\n' +
        '</div>',
      r: [Object],
      t: '本地手动合并Github上的Pull requests',
      i: 'fa-light fa-code-pull-request',
      y: 'a'
    }
  }
] >
  at <BaseTransition onAppear=fn onAfterAppear=fn<n2> onEnter=fn  ... >
  at <Transition name="drop" appear=true onAppear=fn<l2>  ... >
  at <DropTransition appear=true delay=0.24 >
  at <BlogHomePage>
  at <N$1>
  at <CommonWrapper noSidebar=true noToc=true >
  at <BlogWrapper>
  at <BlogHome>
  at <Vuepress>
✖ Rendering 57 pages - failed in 1.00s
error TypeError: Cannot read properties of undefined (reading 'path')
    at file:///C:/Users/qq593/Documents/Vue-Blog/Vue-blog-Dev/src/.vuepress/.temp/.server/app.BJGi5UsY.mjs:3231:100
    at Array.map (<anonymous>)
    at ComputedRefImpl.fn (file:///C:/Users/qq593/Documents/Vue-Blog/Vue-blog-Dev/src/.vuepress/.temp/.server/app.BJGi5UsY.mjs:3231:52)
    at refreshComputed (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\reactivity\dist\reactivity.cjs.js:384:28)
    at get value (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1625:5)
    at ComputedRefImpl.fn (file:///C:/Users/qq593/Documents/Vue-Blog/Vue-blog-Dev/src/.vuepress/.temp/.server/app.BJGi5UsY.mjs:3239:163)
    at refreshComputed (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\reactivity\dist\reactivity.cjs.js:384:28)
    at get value (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1625:5)
    at Proxy.<anonymous> (file:///C:/Users/qq593/Documents/Vue-Blog/Vue-blog-Dev/src/.vuepress/.temp/.server/app.BJGi5UsY.mjs:3285:157)
    at renderComponentRoot (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6445:16)
    at renderComponentSubTree (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:461:28)
    at renderComponentVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:394:12)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:507:14)
    at renderComponentSubTree (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:459:7)
    at renderComponentVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:394:12)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:507:14)
    at renderComponentSubTree (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:409:5)
    at renderComponentVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:394:12)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:507:14)
    at renderComponentSubTree (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:459:7)
    at renderComponentVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:394:12)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:507:14)
    at renderVNodeChildren (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:523:5)
    at renderElementVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:567:9)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:505:9)
    at renderComponentSubTree (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:459:7)
    at renderComponentVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:394:12)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:507:14)
    at renderComponentSubTree (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:459:7)
    at renderComponentVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:394:12)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:507:14)
    at renderComponentSubTree (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:409:5)
    at renderComponentVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:394:12)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:507:14)
    at renderComponentSubTree (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:459:7)
    at renderComponentVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:394:12)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:507:14)
    at renderVNodeChildren (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:523:5)
    at renderElementVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:567:9)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:505:9)
    at renderVNodeChildren (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:523:5)
    at renderElementVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:567:9)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:505:9)
    at renderVNodeChildren (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:523:5)
    at renderElementVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:567:9)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:505:9)
    at renderComponentSubTree (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:459:7)
    at renderComponentVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:394:12)
    at renderVNode (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:507:14)
    at renderVNodeChildren (C:\Users\qq593\Documents\Vue-Blog\Vue-blog-Dev\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:523:5)
```

**Comment by rehnertz** [comment]
I also found that `/FOLDER/README.md` with `article = true` will cause an error of undefined `path` in homepage, whose actual URL is `/FOLDER/` instead of `/FOLDER.html`.

**Comment by Henvy-Mango** [comment]
same here

**Comment by JQiue** [comment]
This problem is very easy to reproduction. When a markdown frontmatter `article` is `true` (This value is the default, even if it is not set), this problem will occur if there is a `category`. Setting the `article` to `false` will run normally. Even if `cartegroy` exists
