### ISSUE TITLE
[Bug] Cannot install theme and init project

### ISSUE THREAD

**Issue by npetersen2** [vuepress-theme-hope/vuepress-theme-hope#590]
Following the instructions for creating a new project using this theme:

```
yarn create vuepress-theme-hope docs
```

results in the following error:

```
Generating Template...
Installing Deps...
This may take a few minutes, please be patient.
We can not correctly output progress bar from child process, so the process may look stuck.
(node:13115) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npm install --registry https://registry.npm.taobao.org
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @mr-hope/vuepress-plugin-components@1.13.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/npetersen/.npm/_logs/2021-04-01T00_34_03_086Z-debug.log
    at makeError (/home/npetersen/.config/yarn/global/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/home/npetersen/.config/yarn/global/node_modules/execa/index.js:186:17)
    at CAC.<anonymous> (/home/npetersen/.config/yarn/global/node_modules/create-vuepress-theme-hope/lib/index.js:89:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13115) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13115) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 126.77s.
```

I am running Ubuntu 16.04 LTS. Latest stable node, npm, yarn.

**Comment by Mister-Hope** [comment]
Please install deps manually.

This is a bug, taobao npm registry should only be used when language is set to Chinese.

**Comment by npetersen2** [comment]
Excellent, I retried all steps in the tutorial after changing yarn to: `yarn config set registry https://registry.npmjs.org`

It works now!

Thanks @Mister-Hope
