### ISSUE TITLE
[Bug] 安装失败

### ISSUE THREAD

**Issue by Purple-CSGO** [vuepress-theme-hope/vuepress-theme-hope#596]
。。。很奇怪，但是的确发生了，yarn和npm指令都会有报错，我在x86 windows环境和arm m1 mac上都试了，日志如下：

## arm mac

```
purp1e@MacBook-2077 Github % npm init vuepress-theme-hope blog         
? Select a language to display en-US
Getting lastest version of deps...
/Users/purp1e/.config/yarn/global/node_modules/create-vuepress-theme-hope/lib/checkVersion.js:16
            reject(new Error(`Get ${packageName} version failed, please check your network!`));
                   ^

Error: Get vuepress version failed, please check your network!
    at ClientRequest.<anonymous> (/Users/purp1e/.config/yarn/global/node_modules/create-vuepress-theme-hope/lib/checkVersion.js:16:20)
    at Object.onceWrapper (node:events:476:26)
    at ClientRequest.emit (node:events:369:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:646:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
    at TLSSocket.socketOnData (node:_http_client:512:22)
    at TLSSocket.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:227:10)
npm ERR! code 1
npm ERR! path /Users/purp1e/Github
npm ERR! command failed
npm ERR! command sh -c create-vuepress-theme-hope "blog"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/purp1e/.npm/_logs/2021-04-18T03_58_22_670Z-debug.log
```

### ⬆️ debug.log日志内容

```
0 verbose cli [
0 verbose cli   '/opt/homebrew/Cellar/node/15.14.0/bin/node',
0 verbose cli   '/opt/homebrew/bin/npm',
0 verbose cli   'init',
0 verbose cli   'vuepress-theme-hope',
0 verbose cli   'blog'
0 verbose cli ]
1 info using npm@7.7.6
2 info using node@v15.14.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 0ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/purp1e/Github/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/Users/purp1e/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 3ms
18 timing npm:load:configload Completed in 3ms
19 timing npm:load:setTitle Completed in 3ms
20 timing npm:load:setupLog Completed in 0ms
21 timing npm:load:cleanupLog Completed in 1ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 0ms
24 timing npm:load Completed in 7ms
25 timing config:load:flatten Completed in 1ms
26 timing config:load:flatten Completed in 0ms
27 timing command:exec Completed in 37277ms
28 timing command:init Completed in 37300ms
29 verbose stack Error: command failed
29 verbose stack     at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
29 verbose stack     at ChildProcess.emit (node:events:369:20)
29 verbose stack     at maybeClose (node:internal/child_process:1067:16)
29 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
30 verbose cwd /Users/purp1e/Github
31 verbose Darwin 20.3.0
32 verbose argv "/opt/homebrew/Cellar/node/15.14.0/bin/node" "/opt/homebrew/bin/npm" "init" "vuepress-theme-hope" "blog"
33 verbose node v15.14.0
34 verbose npm  v7.7.6
35 error code 1
36 error path /Users/purp1e/Github
37 error command failed
38 error command sh -c create-vuepress-theme-hope "blog"
39 verbose exit 1
```

## x86 win
```
PS E:\GitHub-Repo> yarn create vuepress-theme-hope blog
yarn create v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-vuepress-theme-hope@1.14.4" with binaries:
      - create-vuepress-theme-hope
? Select a language to display en-US
Getting lastest version of deps...
(node:13360) UnhandledPromiseRejectionWarning: Error: Get vuepress version failed, please check your network!
    at ClientRequest.<anonymous> (C:\Users\Purp1e\AppData\Local\Yarn\Data\global\node_modules\create-vuepress-theme-hope\lib\checkVersion.js:19:16)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13360) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 24.25s.
```

**Comment by Mister-Hope** [comment]
请检查你的网络环境是否无法访问 npm 官方源。

**Comment by Mister-Hope** [comment]
切换网络是否有帮助？

https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/87f942c0af4a42ecaa744c34b153683fc81e8f51/packages/create/src/checkVersion.ts#L1-L7

我使用的是 node 原生的 https 模块，如果 reject 只能说你没法访问 https://registry.npmjs.org。

暂时关闭了，你使用一个可以访问 npm 官方源的网络应该是没问题的，如果有新问题欢迎开新 issue。
